from django.conf import settings

GOOGLE_ANALYTICS_PROPERTY_ID = getattr(settings, "GOOGLE_ANALYTICS_PROPERTY_ID", None)
GOOGLE_ANALYTICS_DOMAIN = getattr(settings, "GOOGLE_ANALYTICS_DOMAIN", "auto")
GOOGLE_ANALYTICS_ANONYMIZE_IP = getattr(
    settings, "GOOGLE_ANALYTICS_ANONYMIZE_IP", False
)
GOOGLE_ANALYTICS_SAMPLE_RATE = getattr(settings, "GOOGLE_ANALYTICS_SAMPLE_RATE", 100)
GOOGLE_ANALYTICS_SITE_SPEED_SAMPLE_RATE = getattr(
    settings, "GOOGLE_ANALYTICS_SITE_SPEED_SAMPLE_RATE", 1
)
GOOGLE_ANALYTICS_COOKIE_EXPIRES = getattr(
    settings, "GOOGLE_ANALYTICS_COOKIE_EXPIRES", 63072000
)
GOOGLE_ANALYTICS_DISPLAY_FEATURES = getattr(
    settings, "GOOGLE_ANALYTICS_DISPLAY_FEATURES", False
)
GOOGLE_ANALYTICS_USE_GTAG = getattr(settings, "GOOGLE_ANALYTICS_USE_GTAG", True)
GOOGLE_ANALYTICS_DEBUG_MODE = getattr(settings, "GOOGLE_ANALYTICS_DEBUG_MODE", False)
