
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-06T17:19:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b25bb0de9870ea44aac2829968f4f88c857360ec",
 "version": "1.8.63"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
