from typing import overload
import ghidra.pcode.struct
import ghidra.pcode.struct.StructuredSleigh
import ghidra.program.model.address
import ghidra.program.model.data
import java.lang


class CallExpr(ghidra.pcode.struct.Expr):
    """
    A p-code userop invocation expression
 
 
     Userops are essentially treated as functions. They can be invoked passing a list of parameters,
     and the expression takes the value it returns (via StructuredSleigh#_result(RVal).
    """









    def addf(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def addi(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def addi(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def andb(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def andb(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def andi(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def andi(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def cast(self, type: ghidra.program.model.data.DataType) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def deref(self) -> ghidra.pcode.struct.StructuredSleigh.LVal: ...

    @overload
    def deref(self, __a0: ghidra.program.model.address.AddressSpace) -> ghidra.pcode.struct.StructuredSleigh.LVal: ...

    def divf(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def divis(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def divis(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def diviu(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def diviu(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def eq(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def eq(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def eqf(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def equals(self, __a0: object) -> bool: ...

    def generate(self, parent: ghidra.pcode.struct.RValInternal) -> ghidra.pcode.struct.StringTree: ...

    def getClass(self) -> java.lang.Class: ...

    def getContext(self) -> ghidra.pcode.struct.StructuredSleigh: ...

    def getType(self) -> ghidra.program.model.data.DataType: ...

    def gtef(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def gteis(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def gteis(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def gteiu(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def gteiu(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def gtf(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def gtis(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def gtis(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def gtiu(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def gtiu(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def hashCode(self) -> int: ...

    def ltef(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def lteis(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def lteis(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def lteiu(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def lteiu(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def ltf(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def ltis(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def ltis(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def ltiu(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def ltiu(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def mulf(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def muli(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def muli(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def neq(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def neq(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def neqf(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def notb(self) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def noti(self) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @overload
    def orb(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def orb(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def ori(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def ori(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def remis(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def remis(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def remiu(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def remiu(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def shli(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def shli(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def shris(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def shris(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def shriu(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def shriu(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def subf(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def subi(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def subi(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @overload
    def xorb(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def xorb(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def xori(self, __a0: long) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

    @overload
    def xori(self, __a0: ghidra.pcode.struct.StructuredSleigh.RVal) -> ghidra.pcode.struct.StructuredSleigh.RVal: ...

