from typing import List
from typing import overload
import ghidra.pcode.struct
import ghidra.pcode.struct.StructuredSleigh
import ghidra.program.model.data
import java.lang


class DefaultUseropDecl(object, ghidra.pcode.struct.StructuredSleigh.UseropDecl):




    def __init__(self, __a0: ghidra.pcode.struct.StructuredSleigh, __a1: ghidra.program.model.data.DataType, __a2: unicode, __a3: List[object]): ...



    def call(self, args: List[ghidra.pcode.struct.StructuredSleigh.RVal]) -> ghidra.pcode.struct.StructuredSleigh.StmtWithVal: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getName(self) -> unicode: ...

    def getParameterTypes(self) -> List[ghidra.program.model.data.DataType]: ...

    def getReturnType(self) -> ghidra.program.model.data.DataType: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def name(self) -> unicode: ...

    @property
    def parameterTypes(self) -> List[object]: ...

    @property
    def returnType(self) -> ghidra.program.model.data.DataType: ...