# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/mlf_engine_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?modules/perception/pipeline/proto/stage/mlf_engine_config.proto\x12\x17\x61pollo.perception.lidar\"\xde\x01\n\x0fMlfEngineConfig\x12\x13\n\x0bmain_sensor\x18\x01 \x03(\t\x12%\n\x17use_histogram_for_match\x18\x02 \x01(\x08:\x04true\x12\x1e\n\x12histogram_bin_size\x18\x03 \x01(\r:\x02\x31\x30\x12%\n\x16output_predict_objects\x18\x04 \x01(\x08:\x05\x66\x61lse\x12$\n\x17reserved_invisible_time\x18\x05 \x01(\x01:\x03\x30.2\x12\"\n\x13use_frame_timestamp\x18\x06 \x01(\x08:\x05\x66\x61lse')



_MLFENGINECONFIG = DESCRIPTOR.message_types_by_name['MlfEngineConfig']
MlfEngineConfig = _reflection.GeneratedProtocolMessageType('MlfEngineConfig', (_message.Message,), {
  'DESCRIPTOR' : _MLFENGINECONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.mlf_engine_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.MlfEngineConfig)
  })
_sym_db.RegisterMessage(MlfEngineConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MLFENGINECONFIG._serialized_start=93
  _MLFENGINECONFIG._serialized_end=315
# @@protoc_insertion_point(module_scope)
