# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/object_builder_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCmodules/perception/pipeline/proto/stage/object_builder_config.proto\x12\x17\x61pollo.perception.lidar\"\x15\n\x13ObjectBuilderConfig')



_OBJECTBUILDERCONFIG = DESCRIPTOR.message_types_by_name['ObjectBuilderConfig']
ObjectBuilderConfig = _reflection.GeneratedProtocolMessageType('ObjectBuilderConfig', (_message.Message,), {
  'DESCRIPTOR' : _OBJECTBUILDERCONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.object_builder_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.ObjectBuilderConfig)
  })
_sym_db.RegisterMessage(ObjectBuilderConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTBUILDERCONFIG._serialized_start=96
  _OBJECTBUILDERCONFIG._serialized_end=117
# @@protoc_insertion_point(module_scope)
