# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/camera_detection_single_stage/detector/smoke/proto/model_param.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_modules.modules.perception.common.proto import model_info_pb2 as modules_dot_perception_dot_common_dot_proto_dot_model__info__pb2
from apollo_modules.modules.perception.common.proto import model_process_pb2 as modules_dot_perception_dot_common_dot_proto_dot_model__process__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nWmodules/perception/camera_detection_single_stage/detector/smoke/proto/model_param.proto\x12\x1e\x61pollo.perception.camera.smoke\x1a\x30modules/perception/common/proto/model_info.proto\x1a\x33modules/perception/common/proto/model_process.proto\"\xee\x02\n\nModelParam\x12\x31\n\x04info\x18\x01 \x01(\x0b\x32#.apollo.perception.common.ModelInfo\x12\x30\n\x06resize\x18\x02 \x01(\x0b\x32 .apollo.perception.common.Resize\x12\x36\n\tnormalize\x18\x03 \x01(\x0b\x32#.apollo.perception.common.Normalize\x12\x41\n\x0coffset_ratio\x18\x04 \x01(\x0b\x32+.apollo.perception.camera.smoke.OffsetRatio\x12\x1c\n\x14\x63onfidence_threshold\x18\x05 \x01(\x02\x12\x39\n\x08min_dims\x18\x06 \x01(\x0b\x32\'.apollo.perception.camera.smoke.MinDims\x12\x11\n\tori_cycle\x18\x07 \x01(\x05\x12\x14\n\x0c\x62order_ratio\x18\x08 \x01(\x02\"#\n\x0bOffsetRatio\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"d\n\x07MinDims\x12\x15\n\rmin_2d_height\x18\x01 \x01(\x02\x12\x15\n\rmin_3d_height\x18\x02 \x01(\x02\x12\x14\n\x0cmin_3d_width\x18\x03 \x01(\x02\x12\x15\n\rmin_3d_length\x18\x04 \x01(\x02')



_MODELPARAM = DESCRIPTOR.message_types_by_name['ModelParam']
_OFFSETRATIO = DESCRIPTOR.message_types_by_name['OffsetRatio']
_MINDIMS = DESCRIPTOR.message_types_by_name['MinDims']
ModelParam = _reflection.GeneratedProtocolMessageType('ModelParam', (_message.Message,), {
  'DESCRIPTOR' : _MODELPARAM,
  '__module__' : 'modules.perception.camera_detection_single_stage.detector.smoke.proto.model_param_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.smoke.ModelParam)
  })
_sym_db.RegisterMessage(ModelParam)

OffsetRatio = _reflection.GeneratedProtocolMessageType('OffsetRatio', (_message.Message,), {
  'DESCRIPTOR' : _OFFSETRATIO,
  '__module__' : 'modules.perception.camera_detection_single_stage.detector.smoke.proto.model_param_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.smoke.OffsetRatio)
  })
_sym_db.RegisterMessage(OffsetRatio)

MinDims = _reflection.GeneratedProtocolMessageType('MinDims', (_message.Message,), {
  'DESCRIPTOR' : _MINDIMS,
  '__module__' : 'modules.perception.camera_detection_single_stage.detector.smoke.proto.model_param_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.smoke.MinDims)
  })
_sym_db.RegisterMessage(MinDims)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELPARAM._serialized_start=227
  _MODELPARAM._serialized_end=593
  _OFFSETRATIO._serialized_start=595
  _OFFSETRATIO._serialized_end=630
  _MINDIMS._serialized_start=632
  _MINDIMS._serialized_end=732
# @@protoc_insertion_point(module_scope)
