# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/plugin/pointcloud_get_objects_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLmodules/perception/pipeline/proto/plugin/pointcloud_get_objects_config.proto\x12\x17\x61pollo.perception.lidar\"\x1c\n\x1aPointcloudGetObjectsConfig')



_POINTCLOUDGETOBJECTSCONFIG = DESCRIPTOR.message_types_by_name['PointcloudGetObjectsConfig']
PointcloudGetObjectsConfig = _reflection.GeneratedProtocolMessageType('PointcloudGetObjectsConfig', (_message.Message,), {
  'DESCRIPTOR' : _POINTCLOUDGETOBJECTSCONFIG,
  '__module__' : 'modules.perception.pipeline.proto.plugin.pointcloud_get_objects_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.PointcloudGetObjectsConfig)
  })
_sym_db.RegisterMessage(PointcloudGetObjectsConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTCLOUDGETOBJECTSCONFIG._serialized_start=105
  _POINTCLOUDGETOBJECTSCONFIG._serialized_end=133
# @@protoc_insertion_point(module_scope)
