from textual_cogs.dialogs.quit_dialog import QuitDialog
from textual_cogs.dialogs.message_dialog import MessageDialog
from textual_cogs.dialogs.save_dialog import SaveFileDialog
from textual_cogs.dialogs.single_choice_dialog import SingleChoiceDialog
from textual_cogs.dialogs.single_color_picker_dialog import SingleColorPickerDialog
from textual_cogs.dialogs.text_entry_dialog import TextEntryDialog