# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/contrib/lgsvl_msgs/proto/detection3darray.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_modules.modules.common_msgs.basic_msgs import header_pb2 as modules_dot_common__msgs_dot_basic__msgs_dot_header__pb2
from apollo_modules.modules.contrib.lgsvl_msgs.proto import detection3d_pb2 as modules_dot_contrib_dot_lgsvl__msgs_dot_proto_dot_detection3d__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7modules/contrib/lgsvl_msgs/proto/detection3darray.proto\x12\x19\x61pollo.contrib.lgsvl_msgs\x1a+modules/common_msgs/basic_msgs/header.proto\x1a\x32modules/contrib/lgsvl_msgs/proto/detection3d.proto\"u\n\x10\x44\x65tection3DArray\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.apollo.common.Header\x12:\n\ndetections\x18\x02 \x03(\x0b\x32&.apollo.contrib.lgsvl_msgs.Detection3Db\x06proto3')



_DETECTION3DARRAY = DESCRIPTOR.message_types_by_name['Detection3DArray']
Detection3DArray = _reflection.GeneratedProtocolMessageType('Detection3DArray', (_message.Message,), {
  'DESCRIPTOR' : _DETECTION3DARRAY,
  '__module__' : 'modules.contrib.lgsvl_msgs.proto.detection3darray_pb2'
  # @@protoc_insertion_point(class_scope:apollo.contrib.lgsvl_msgs.Detection3DArray)
  })
_sym_db.RegisterMessage(Detection3DArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DETECTION3DARRAY._serialized_start=183
  _DETECTION3DARRAY._serialized_end=300
# @@protoc_insertion_point(module_scope)
