# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/control/controllers/demo_control_task/proto/demo_control_task_conf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPmodules/control/controllers/demo_control_task/proto/demo_control_task_conf.proto\x12\x0e\x61pollo.control\"(\n\x13\x44\x65moControlTaskConf\x12\x11\n\tbound_acc\x18\x01 \x01(\x01')



_DEMOCONTROLTASKCONF = DESCRIPTOR.message_types_by_name['DemoControlTaskConf']
DemoControlTaskConf = _reflection.GeneratedProtocolMessageType('DemoControlTaskConf', (_message.Message,), {
  'DESCRIPTOR' : _DEMOCONTROLTASKCONF,
  '__module__' : 'modules.control.controllers.demo_control_task.proto.demo_control_task_conf_pb2'
  # @@protoc_insertion_point(class_scope:apollo.control.DemoControlTaskConf)
  })
_sym_db.RegisterMessage(DemoControlTaskConf)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEMOCONTROLTASKCONF._serialized_start=100
  _DEMOCONTROLTASKCONF._serialized_end=140
# @@protoc_insertion_point(module_scope)
