"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .zillowpricehistoryevent import (
    ZillowPriceHistoryEvent,
    ZillowPriceHistoryEventTypedDict,
)
from exfunc_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class GetPriceHistoryRequestBodyTypedDict(TypedDict):
    property_id: str
    r"""The ID of the property for which to retrieve price history"""


class GetPriceHistoryRequestBody(BaseModel):
    property_id: str
    r"""The ID of the property for which to retrieve price history"""


class GetPriceHistoryResponseBodyTypedDict(TypedDict):
    r"""GetPropertyPriceHistory API successful response"""

    results: NotRequired[List[ZillowPriceHistoryEventTypedDict]]


class GetPriceHistoryResponseBody(BaseModel):
    r"""GetPropertyPriceHistory API successful response"""

    results: Optional[List[ZillowPriceHistoryEvent]] = None
