# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/tasks/lane_borrow_path/proto/lane_borrow_path.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_modules.modules.planning.planning_base.proto import piecewise_jerk_path_config_pb2 as modules_dot_planning_dot_planning__base_dot_proto_dot_piecewise__jerk__path__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDmodules/planning/tasks/lane_borrow_path/proto/lane_borrow_path.proto\x12\x0f\x61pollo.planning\x1a\x45modules/planning/planning_base/proto/piecewise_jerk_path_config.proto\"\xe0\x01\n\x14LaneBorrowPathConfig\x12G\n\x15path_optimizer_config\x18\x01 \x01(\x0b\x32(.apollo.planning.PiecewiseJerkPathConfig\x12%\n\x17is_allow_lane_borrowing\x18\x02 \x01(\x08:\x04true\x12 \n\x15lane_borrow_max_speed\x18\x03 \x01(\x01:\x01\x35\x12\x36\n+long_term_blocking_obstacle_cycle_threshold\x18\x04 \x01(\x03:\x01\x33')



_LANEBORROWPATHCONFIG = DESCRIPTOR.message_types_by_name['LaneBorrowPathConfig']
LaneBorrowPathConfig = _reflection.GeneratedProtocolMessageType('LaneBorrowPathConfig', (_message.Message,), {
  'DESCRIPTOR' : _LANEBORROWPATHCONFIG,
  '__module__' : 'modules.planning.tasks.lane_borrow_path.proto.lane_borrow_path_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.LaneBorrowPathConfig)
  })
_sym_db.RegisterMessage(LaneBorrowPathConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANEBORROWPATHCONFIG._serialized_start=161
  _LANEBORROWPATHCONFIG._serialized_end=385
# @@protoc_insertion_point(module_scope)
