# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/common_msgs/planning_msgs/sl_boundary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_modules.modules.common_msgs.basic_msgs import pnc_point_pb2 as modules_dot_common__msgs_dot_basic__msgs_dot_pnc__point__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3modules/common_msgs/planning_msgs/sl_boundary.proto\x12\x0f\x61pollo.planning\x1a.modules/common_msgs/basic_msgs/pnc_point.proto\"|\n\nSLBoundary\x12\x0f\n\x07start_s\x18\x01 \x01(\x01\x12\r\n\x05\x65nd_s\x18\x02 \x01(\x01\x12\x0f\n\x07start_l\x18\x03 \x01(\x01\x12\r\n\x05\x65nd_l\x18\x04 \x01(\x01\x12.\n\x0e\x62oundary_point\x18\x05 \x03(\x0b\x32\x16.apollo.common.SLPoint')



_SLBOUNDARY = DESCRIPTOR.message_types_by_name['SLBoundary']
SLBoundary = _reflection.GeneratedProtocolMessageType('SLBoundary', (_message.Message,), {
  'DESCRIPTOR' : _SLBOUNDARY,
  '__module__' : 'modules.common_msgs.planning_msgs.sl_boundary_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.SLBoundary)
  })
_sym_db.RegisterMessage(SLBoundary)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SLBOUNDARY._serialized_start=120
  _SLBOUNDARY._serialized_end=244
# @@protoc_insertion_point(module_scope)
