# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/center_point_detection_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKmodules/perception/pipeline/proto/stage/center_point_detection_config.proto\x12\x17\x61pollo.perception.lidar\"\x1c\n\x1a\x43\x65nterPointDetectionConfig')



_CENTERPOINTDETECTIONCONFIG = DESCRIPTOR.message_types_by_name['CenterPointDetectionConfig']
CenterPointDetectionConfig = _reflection.GeneratedProtocolMessageType('CenterPointDetectionConfig', (_message.Message,), {
  'DESCRIPTOR' : _CENTERPOINTDETECTIONCONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.center_point_detection_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.CenterPointDetectionConfig)
  })
_sym_db.RegisterMessage(CenterPointDetectionConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CENTERPOINTDETECTIONCONFIG._serialized_start=104
  _CENTERPOINTDETECTIONCONFIG._serialized_end=132
# @@protoc_insertion_point(module_scope)
