# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/pipeline/proto/stage/pointcloud_detection_preprocessor_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nVmodules/perception/pipeline/proto/stage/pointcloud_detection_preprocessor_config.proto\x12\x17\x61pollo.perception.lidar\"\'\n%PointcloudDetectionPreprocessorConfig')



_POINTCLOUDDETECTIONPREPROCESSORCONFIG = DESCRIPTOR.message_types_by_name['PointcloudDetectionPreprocessorConfig']
PointcloudDetectionPreprocessorConfig = _reflection.GeneratedProtocolMessageType('PointcloudDetectionPreprocessorConfig', (_message.Message,), {
  'DESCRIPTOR' : _POINTCLOUDDETECTIONPREPROCESSORCONFIG,
  '__module__' : 'modules.perception.pipeline.proto.stage.pointcloud_detection_preprocessor_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.PointcloudDetectionPreprocessorConfig)
  })
_sym_db.RegisterMessage(PointcloudDetectionPreprocessorConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POINTCLOUDDETECTIONPREPROCESSORCONFIG._serialized_start=115
  _POINTCLOUDDETECTIONPREPROCESSORCONFIG._serialized_end=154
# @@protoc_insertion_point(module_scope)
