from typing import overload
import ghidra.pcode.emu
import ghidra.program.model.lang
import java.lang


class X86PcodeStateInitializer(object, ghidra.pcode.emu.PcodeStateInitializer):




    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def initializeMachine(self, __a0: ghidra.pcode.emu.PcodeMachine) -> None: ...

    def initializeThread(self, thread: ghidra.pcode.emu.PcodeThread) -> None: ...

    def isApplicable(self, language: ghidra.program.model.lang.Language) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

