from .gaussiana import gaussiana
from .gaussiana_compuesta import gaussiana_compuesta
from .gaussiana_compuesta_iterativa import gaussiana_compuesta_iterativa
from .simpson import simpson
from .simpson_compuesto import simpson_compuesto
from .simpson_compuesto_iterativo import simpson_compuesto_iterativo
from .trapecio import trapecio
from .trapecio_compuesto import trapecio_compuesto
from .trapecio_compuesto_iterativo import trapecio_compuesto_iterativo
from .romberg import romberg