
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-07T00:00:34+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba14445dd6c645f16cb3e45581044d65088eaf1f",
 "version": "7.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
