AGGREGATOR_GAS_COST = 400_000
BATCHER_SUBMISSION_BASE_GAS_COST = 125_000
ADDITIONAL_SUBMISSION_GAS_COST_PER_PROOF = 13_000

# Percentage modifiers (100% is x1, 10% is x0.1, 1000% is x10)
RESPOND_TO_TASK_FEE_LIMIT_PERCENTAGE_MULTIPLIER = 250
DEFAULT_AGGREGATOR_FEE_PERCENTAGE_MULTIPLIER = 150
GAS_PRICE_PERCENTAGE_MULTIPLIER = 110
PERCENTAGE_DIVIDER = 100

# Calculated constants
CONSTANT_GAS_COST = (
    (AGGREGATOR_GAS_COST * DEFAULT_AGGREGATOR_FEE_PERCENTAGE_MULTIPLIER) // 
    PERCENTAGE_DIVIDER + BATCHER_SUBMISSION_BASE_GAS_COST
)

DEFAULT_MAX_FEE_PER_PROOF = ADDITIONAL_SUBMISSION_GAS_COST_PER_PROOF * 100_000_000_000  # gas_price = 100 Gwei
MIN_FEE_PER_PROOF = ADDITIONAL_SUBMISSION_GAS_COST_PER_PROOF * 100_000_000  # gas_price = 0.1 Gwei

# SDK
MAX_FEE_BATCH_PROOF_NUMBER = 32
MAX_FEE_DEFAULT_PROOF_NUMBER = 10