# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/control/control_component/proto/pipeline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_modules.modules.control.control_component.proto import plugin_declare_info_pb2 as modules_dot_control_dot_control__component_dot_proto_dot_plugin__declare__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6modules/control/control_component/proto/pipeline.proto\x12\x0e\x61pollo.control\x1a\x41modules/control/control_component/proto/plugin_declare_info.proto\"H\n\x0f\x43ontrolPipeline\x12\x35\n\ncontroller\x18\x01 \x03(\x0b\x32!.apollo.control.PluginDeclareInfo')



_CONTROLPIPELINE = DESCRIPTOR.message_types_by_name['ControlPipeline']
ControlPipeline = _reflection.GeneratedProtocolMessageType('ControlPipeline', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLPIPELINE,
  '__module__' : 'modules.control.control_component.proto.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:apollo.control.ControlPipeline)
  })
_sym_db.RegisterMessage(ControlPipeline)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTROLPIPELINE._serialized_start=141
  _CONTROLPIPELINE._serialized_end=213
# @@protoc_insertion_point(module_scope)
