# Generated by Django 5.1.2 on 2024-11-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_account_tag_alter_accountingentry_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountingentry",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
