from typing import overload
import ghidra.pty
import java.lang


class SshPty(object, ghidra.pty.Pty):




    def __init__(self, channel: com.jcraft.jsch.ChannelExec): ...



    def close(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getChild(self) -> ghidra.pty.PtyChild: ...

    def getClass(self) -> java.lang.Class: ...

    def getParent(self) -> ghidra.pty.PtyParent: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def child(self) -> ghidra.pty.PtyChild: ...

    @property
    def parent(self) -> ghidra.pty.PtyParent: ...