from typing import List
from typing import overload
import ghidra.pty
import ghidra.pty.ssh
import java.io
import java.lang
import java.util


class SshPtyChild(ghidra.pty.ssh.SshPtyEndpoint, ghidra.pty.PtyChild):




    def __init__(self, channel: com.jcraft.jsch.ChannelExec, outputStream: java.io.OutputStream, inputStream: java.io.InputStream): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getInputStream(self) -> java.io.InputStream: ...

    def getOutputStream(self) -> java.io.OutputStream: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @overload
    def nullSession(self, __a0: List[ghidra.pty.PtyChild.TermMode]) -> unicode: ...

    @overload
    def nullSession(self, mode: java.util.Collection) -> unicode: ...

    @overload
    def session(self, __a0: List[unicode], __a1: java.util.Map, __a2: List[ghidra.pty.PtyChild.TermMode]) -> ghidra.pty.PtySession: ...

    @overload
    def session(self, __a0: List[unicode], __a1: java.util.Map, __a2: java.io.File, __a3: List[ghidra.pty.PtyChild.TermMode]) -> ghidra.pty.PtySession: ...

    @overload
    def session(self, args: List[unicode], env: java.util.Map, workingDirectory: java.io.File, mode: java.util.Collection) -> ghidra.pty.ssh.SshPtySession: ...

    def setWindowSize(self, cols: int, rows: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def inputStream(self) -> java.io.InputStream: ...

    @property
    def outputStream(self) -> java.io.OutputStream: ...