from testapp.perms.apps.account import (
    INVITE_DELETE,
    INVITE_MANAGE,
    PERMISSION_DELETE,
    PERMISSION_MANAGE,
    PROFILE_DELETE,
    PROFILE_MANAGE,
    ROLE_DELETE,
    ROLE_MANAGE,
    USER_DELETE,
    USER_MANAGE,
)
from testapp.perms.apps.org_structure import (
    BRANCH_DELETE,
    BRANCH_MANAGE,
    DEPARTMENT_DELETE,
    DEPARTMENT_MANAGE,
    ORGANISATION_DELETE,
    ORGANISATION_MANAGE,
)

PROFILE_ADMIN = [PROFILE_MANAGE]

DEPARTMENT_ADMIN = [
    INVITE_MANAGE,
]

BRANCH_ADMIN = [
    DEPARTMENT_MANAGE,
    ROLE_MANAGE,
]

BRANCH_ADMIN = BRANCH_ADMIN + DEPARTMENT_ADMIN + PROFILE_ADMIN

ORGANISATION_ADMIN = [
    ORGANISATION_MANAGE,
    BRANCH_MANAGE,
    BRANCH_DELETE,
    DEPARTMENT_DELETE,
    ROLE_DELETE,
]

ORGANISATION_ADMIN += BRANCH_ADMIN

NETWORK_ADMIN = [
    ORGANISATION_DELETE,
    USER_MANAGE,
    USER_DELETE,
    PERMISSION_MANAGE,
    PERMISSION_DELETE,
    PROFILE_DELETE,
    INVITE_DELETE,
]

NETWORK_ADMIN += ORGANISATION_ADMIN
