from typing import Iterator
from typing import overload
import java.lang
import java.util
import java.util.function


class CancellableIterator(object, java.util.Iterator):
    """
    An Iterator wrapper that allows clients to use a task monitor to cancel iteration
    """





    def __init__(self, delegate: Iterator[object], monitor: ghidra.util.task.TaskMonitor): ...

    def __iter__(self) -> Iterator[object]: ...

    def equals(self, __a0: object) -> bool: ...

    def forEachRemaining(self, __a0: java.util.function.Consumer) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def hasNext(self) -> bool: ...

    def hashCode(self) -> int: ...

    def next(self) -> object: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def remove(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

