# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/common/util/testdata/simple.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_modules.modules.common_msgs.basic_msgs import header_pb2 as modules_dot_common__msgs_dot_basic__msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)modules/common/util/testdata/simple.proto\x12\x17\x61pollo.common.util.test\x1a+modules/common_msgs/basic_msgs/header.proto\"U\n\rSimpleMessage\x12\x0f\n\x07integer\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\x12%\n\x06header\x18\x03 \x01(\x0b\x32\x15.apollo.common.Header\"P\n\x15SimpleRepeatedMessage\x12\x37\n\x07message\x18\x01 \x03(\x0b\x32&.apollo.common.util.test.SimpleMessage')



_SIMPLEMESSAGE = DESCRIPTOR.message_types_by_name['SimpleMessage']
_SIMPLEREPEATEDMESSAGE = DESCRIPTOR.message_types_by_name['SimpleRepeatedMessage']
SimpleMessage = _reflection.GeneratedProtocolMessageType('SimpleMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEMESSAGE,
  '__module__' : 'modules.common.util.testdata.simple_pb2'
  # @@protoc_insertion_point(class_scope:apollo.common.util.test.SimpleMessage)
  })
_sym_db.RegisterMessage(SimpleMessage)

SimpleRepeatedMessage = _reflection.GeneratedProtocolMessageType('SimpleRepeatedMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEREPEATEDMESSAGE,
  '__module__' : 'modules.common.util.testdata.simple_pb2'
  # @@protoc_insertion_point(class_scope:apollo.common.util.test.SimpleRepeatedMessage)
  })
_sym_db.RegisterMessage(SimpleRepeatedMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMPLEMESSAGE._serialized_start=115
  _SIMPLEMESSAGE._serialized_end=200
  _SIMPLEREPEATEDMESSAGE._serialized_start=202
  _SIMPLEREPEATEDMESSAGE._serialized_end=282
# @@protoc_insertion_point(module_scope)
