from typing import List
from typing import overload
import docking.action
import ghidra.plugins.fsbrowser
import java.lang


class OpenFsFSBFileHandler(object, ghidra.plugins.fsbrowser.FSBFileHandler):
    FSB_OPEN_FILE_SYSTEM_CHOOSER: unicode = u'FSB Open File System Chooser'
    FSB_OPEN_FILE_SYSTEM_IN_NEW_WINDOW: unicode = u'FSB Open File System In New Window'
    FSB_OPEN_FILE_SYSTEM_NESTED: unicode = u'FSB Open File System Nested'



    def __init__(self): ...



    def createActions(self) -> List[docking.action.DockingAction]: ...

    def equals(self, __a0: object) -> bool: ...

    def fileDefaultAction(self, __a0: ghidra.plugins.fsbrowser.FSBFileNode) -> bool: ...

    def fileFocused(self, __a0: ghidra.plugins.fsbrowser.FSBFileNode) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getPopupProviderActions(self) -> List[object]: ...

    def hashCode(self) -> int: ...

    def init(self, context: ghidra.plugins.fsbrowser.FSBFileHandlerContext) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def popupProviderActions(self) -> List[object]: ...