# Generated by Django 5.0.6 on 2024-10-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20241017_2148"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personcontact",
            options={
                "verbose_name": "person_contact",
                "verbose_name_plural": "person_contacts",
            },
        ),
        migrations.AddIndex(
            model_name="personcontact",
            index=models.Index(fields=["contact_value"], name="contact_value_idx"),
        ),
        migrations.AddIndex(
            model_name="personcontact",
            index=models.Index(fields=["contact_type"], name="contact_type_idx"),
        ),
    ]
