# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bpln_proto/commander/service/v2/bauplan_info.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n2bpln_proto/commander/service/v2/bauplan_info.proto\x12\x1f\x62pln_proto.commander.service.v2"%\n\x12\x42\x61uplanInfoRequest\x12\x0f\n\x07\x61pi_key\x18\x01 \x01(\t"<\n\x0eRunnerNodeInfo\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\tJ\x04\x08\x03\x10\x04"\x8d\x01\n\x0b\x42\x61uplanInfo\x12@\n\x07runners\x18\x01 \x03(\x0b\x32/.bpln_proto.commander.service.v2.RunnerNodeInfo\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x03 \x01(\t\x12\x16\n\x0eserver_version\x18\x04 \x01(\tB-Z+github.com/BauplanLabs/commander/service/v2b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'bpln_proto.commander.service.v2.bauplan_info_pb2', _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/BauplanLabs/commander/service/v2'
    _globals['_BAUPLANINFOREQUEST']._serialized_start = 87
    _globals['_BAUPLANINFOREQUEST']._serialized_end = 124
    _globals['_RUNNERNODEINFO']._serialized_start = 126
    _globals['_RUNNERNODEINFO']._serialized_end = 186
    _globals['_BAUPLANINFO']._serialized_start = 189
    _globals['_BAUPLANINFO']._serialized_end = 330
# @@protoc_insertion_point(module_scope)
