import re
from urllib.parse import unquote
from colorama import Fore, Style, init

# Initialize Colorama
init(autoreset=True)

def detect_xss_payload(payload):
    # Decode URL-encoded characters multiple times to handle various encodings
    decoded_payload = payload
    for _ in range(3):  # Decode up to three times to cover deep encoding
        decoded_payload = unquote(decoded_payload)
    
    # Comprehensive dictionary of XSS patterns with descriptions
    xss_patterns = {
        # Basic XSS patterns
        r"(?i)<script\b[^>]*>(.*?)</script>": "Script Tag",
        r"(?i)javascript:": "JavaScript URI",
        r"(?i)vbscript:": "VBScript URI",
        r"(?i)on\w+=['\"]?[^>]+['\"]?": "Event Handler (onload, onerror, etc.)",
        r"(?i)<\s*img\s+[^>]*src=['\"]?javascript:": "Image Tag with JavaScript URI",
        r"(?i)<\s*img\s+[^>]*src=['\"]?vbscript:": "Image Tag with VBScript URI",
        
        # HTML Elements exploited in XSS
        r"(?i)<\s*iframe\b[^>]*>": "Iframe Tag",
        r"(?i)<\s*svg\b[^>]*>": "SVG Tag",
        r"(?i)<\s*video\b[^>]*>": "Video Tag",
        r"(?i)<\s*audio\b[^>]*>": "Audio Tag",
        r"(?i)<\s*base\b[^>]*href=['\"]?javascript:": "Base Tag with JavaScript URI",
        r"(?i)<\s*input\b[^>]*>": "Input Tag",
        r"(?i)<\s*button\b[^>]*>": "Button Tag",
        r"(?i)<\s*form\b[^>]*action=['\"]?javascript:": "Form Tag with JavaScript URI",
        r"(?i)<\s*embed\b[^>]*src=['\"]?javascript:": "Embed Tag with JavaScript URI",
        r"(?i)<\s*object\b[^>]*>": "Object Tag",
        r"(?i)<\s*applet\b[^>]*>": "Applet Tag",
        r"(?i)<\s*link\s+[^>]*href=['\"]?javascript:": "Link Tag with JavaScript URI",
        r"(?i)<\s*meta\s+[^>]*http-equiv=['\"]?refresh['\"]?[^>]*content=['\"]?0;url=javascript:": "Meta Refresh Tag with JavaScript URI",
        r"(?i)<\s*style\b[^>]*>": "Style Tag",
        r"(?i)<\s*iframe\b[^>]*srcdoc=['\"].*?</iframe>": "Iframe Tag with Srcdoc",
        r"(?i)<\s*img\s+[^>]*onerror=['\"].*?['\"]": "Image Tag with Onerror Event",
        r"(?i)<\s*body\b[^>]*onload=['\"]?[^>]+['\"]?": "Body Tag with onload Event",
        
        # Obfuscated JavaScript Patterns
        r"(?i)srcdoc=['\"].*?<script.*?>": "Srcdoc Attribute with Script",
        r"(?i)eval\((.*?)\)": "Eval Function",
        r"(?i)alert\((.*?)\)": "Alert Function",
        r"(?i)prompt\((.*?)\)": "Prompt Function",
        r"(?i)confirm\((.*?)\)": "Confirm Function",
        r"(?i)document\.cookie": "Document Cookie Access",
        r"(?i)document\.write": "Document Write",
        r"(?i)window\.location": "Window Location Access",
        r"(?i)window\.name": "Window Name Access",
        r"(?i)setTimeout\((.*?)\)": "SetTimeout Function",
        r"(?i)setInterval\((.*?)\)": "SetInterval Function",
        r"(?i)Function\(": "Dynamic Function Constructor",
        r"(?i)unescape\(": "Unescape Function",
        r"(?i)encodeURI\(": "encodeURI Function",
        r"(?i)encodeURIComponent\(": "encodeURIComponent Function",
        r"(?i)decodeURI\(": "decodeURI Function",
        r"(?i)decodeURIComponent\(": "decodeURIComponent Function",
        r"(?i)\bimport\b": "Import Statement",
        r"(?i)\bexport\b": "Export Statement",
        r"(?i)innerHTML": "innerHTML Property",
        r"(?i)outerHTML": "outerHTML Property",
        r"(?i)insertAdjacentHTML": "insertAdjacentHTML Function",
        r"(?i)innerText": "innerText Property",
        r"(?i)textContent": "textContent Property",
        r"(?i)document\.documentElement": "Document Element Access",
        r"(?i)document\.getElementsByTagName": "getElementsByTagName Function",
        r"(?i)document\.getElementById": "getElementById Function",
        r"(?i)document\.querySelector": "querySelector Function",
        r"(?i)document\.querySelectorAll": "querySelectorAll Function",
        
        # HTML/CSS Injection
        r"(?i)<style\b[^>]*>(.*?)</style>": "Style Tag",
        r"(?i)expression\([^)]*\)": "CSS Expression Injection",
        r"(?i)-moz-binding": "Mozilla Binding Injection",
        r"(?i)url\s*\(": "CSS URL Function",
        r"(?i)@import\s+url\(": "CSS @import Rule",
        r"(?i)background\s*:\s*url\(": "CSS Background URL",
        r"(?i)filter\s*:\s*progid:": "CSS Filter with ProgID",
        r"(?i)behavior\s*:\s*url\(": "CSS Behavior URL",
        r"(?i)charset\s*=\s*['\"]?utf-7['\"]?": "Charset UTF-7",
        r"(?i)\/\*.*?\*\/": "CSS Comment Block",
        r"(?i)<!--.*?-->": "HTML Comment Block",
        r"(?i)<!\[CDATA\[.*?\]\]>": "CDATA Section",
        
        # Hexadecimal and Unicode encodings
        r"(?i)(%[0-9A-Fa-f]{2}){1,}": "Hexadecimal Encoding",  # General hex pattern
        r"(?i)&#x[0-9A-Fa-f]{1,6};": "Hexadecimal HTML Entity",
        r"(?i)&#[0-9]{1,6};": "Decimal HTML Entity",
        r"(?i)\\x[0-9A-Fa-f]{2}": "JavaScript Hex Encoding",
        r"(?i)\\u[0-9A-Fa-f]{4}": "Unicode Escape Sequence",
        r"(?i)\/\*.*?\*\/": "Multi-line Comment",
        r"(?i)\/\//.*?$": "Single-line Comment",
        r"(?i)\b0x[0-9A-Fa-f]+\b": "Hexadecimal Number",
        r"(?i)%3C": "Encoded Less-Than Symbol (%3C)",
        r"(?i)%3E": "Encoded Greater-Than Symbol (%3E)",
        r"(?i)%27": "Encoded Single Quote (%27)",
        r"(?i)%22": "Encoded Double Quote (%22)",
        r"(?i)%2F%2F": "Encoded Double Slash (%2F%2F)",
        r"(?i)%3A%2F%2F": "Encoded :// (%3A%2F%2F)",
        r"(?i)%252F": "Double Encoded Slash (%252F)",
        r"(?i)%2527": "Double Encoded Single Quote (%2527)",
        r"(?i)%2522": "Double Encoded Double Quote (%2522)",
        r"(?i)%253C": "Double Encoded Less-Than Symbol (%253C)",
        r"(?i)%253E": "Double Encoded Greater-Than Symbol (%253E)",
        r"(?i)%2540": "Double Encoded At Symbol (%2540)",
        r"(?i)%2520": "Double Encoded Space (%2520)",
        r"(?i)&#x000A;": "Hexadecimal Line Feed",
        r"(?i)&#x000D;": "Hexadecimal Carriage Return",
        r"(?i)&#x0009;": "Hexadecimal Tab",
        r"(?i)&#10;": "Decimal Line Feed",
        r"(?i)&#13;": "Decimal Carriage Return",
        r"(?i)&#9;": "Decimal Tab",
        
        # Inline event handlers and dangerous attributes
        r"(?i)onerror\s*=\s*['\"].*?['\"]": "Onerror Event Handler",
        r"(?i)onmouseover\s*=\s*['\"].*?['\"]": "Onmouseover Event Handler",
        r"(?i)onclick\s*=\s*['\"].*?['\"]": "Onclick Event Handler",
        r"(?i)onfocus\s*=\s*['\"].*?['\"]": "Onfocus Event Handler",
        r"(?i)onmouse\w+\s*=\s*['\"].*?['\"]": "Mouse Event Handler",
        r"(?i)onsubmit\s*=\s*['\"].*?['\"]": "Onsubmit Event Handler",
        r"(?i)onload\s*=\s*['\"].*?['\"]": "Onload Event Handler",
        r"(?i)onunload\s*=\s*['\"].*?['\"]": "Onunload Event Handler",
        r"(?i)onblur\s*=\s*['\"].*?['\"]": "Onblur Event Handler",
        r"(?i)onchange\s*=\s*['\"].*?['\"]": "Onchange Event Handler",
        r"(?i)oninput\s*=\s*['\"].*?['\"]": "Oninput Event Handler",
        r"(?i)onkeydown\s*=\s*['\"].*?['\"]": "Onkeydown Event Handler",
        r"(?i)onkeypress\s*=\s*['\"].*?['\"]": "Onkeypress Event Handler",
        r"(?i)onkeyup\s*=\s*['\"].*?['\"]": "Onkeyup Event Handler",
        r"(?i)ondblclick\s*=\s*['\"].*?['\"]": "Ondblclick Event Handler",
        r"(?i)oncontextmenu\s*=\s*['\"].*?['\"]": "Oncontextmenu Event Handler",
        r"(?i)onresize\s*=\s*['\"].*?['\"]": "Onresize Event Handler",
        r"(?i)onscroll\s*=\s*['\"].*?['\"]": "Onscroll Event Handler",
        r"(?i)onwheel\s*=\s*['\"].*?['\"]": "Onwheel Event Handler",
        r"(?i)ontouchstart\s*=\s*['\"].*?['\"]": "Ontouchstart Event Handler",
        r"(?i)ontouchend\s*=\s*['\"].*?['\"]": "Ontouchend Event Handler",
        r"(?i)ontouchmove\s*=\s*['\"].*?['\"]": "Ontouchmove Event Handler",
        r"(?i)ontouchcancel\s*=\s*['\"].*?['\"]": "Ontouchcancel Event Handler",
        
        # Advanced Payload Patterns
        r"(?i)(document|window|parent|top|self|frames)\.": "Potential DOM Manipulation",
        r"(?i)fetch\((.*?)\)": "Fetch Function",
        r"(?i)ws://": "WebSocket URL",
        r"(?i)wss://": "Secure WebSocket URL",
        r"(?i)socket\.": "Socket Manipulation",
        r"(?i)XMLHttpRequest\.": "XMLHttpRequest Object",
        r"(?i)WebSocket\.": "WebSocket Object",
        r"(?i)Worker\.": "Web Worker",
        r"(?i)SharedWorker\.": "Shared Worker",
        r"(?i)importScripts\(": "importScripts Function",
        r"(?i)document\.referrer": "Document Referrer Access",
        r"(?i)document\.lastModified": "Document Last Modified Access",
        r"(?i)navigator\.userAgent": "Navigator User Agent Access",
        r"(?i)location\.href": "Location Href Access",
        r"(?i)location\.assign": "Location Assign Function",
        r"(?i)location\.replace": "Location Replace Function",
        r"(?i)history\.pushState": "History PushState Function",
        r"(?i)history\.replaceState": "History ReplaceState Function",
        r"(?i)history\.back": "History Back Function",
        r"(?i)history\.forward": "History Forward Function",
        r"(?i)console\.log": "Console Log Function",
        r"(?i)console\.error": "Console Error Function",
        r"(?i)console\.warn": "Console Warn Function",
        r"(?i)console\.info": "Console Info Function",
        r"(?i)console\.debug": "Console Debug Function",
        r"(?i)console\.trace": "Console Trace Function",
        r"(?i)console\.dir": "Console Dir Function",
        r"(?i)console\.dirxml": "Console DirXML Function",
        r"(?i)console\.table": "Console Table Function",
        r"(?i)console\.group": "Console Group Function",
        r"(?i)console\.groupEnd": "Console GroupEnd Function",
        r"(?i)console\.clear": "Console Clear Function",
        r"(?i)console\.count": "Console Count Function",
        r"(?i)console\.assert": "Console Assert Function",
        r"(?i)console\.profile": "Console Profile Function",
        r"(?i)console\.profileEnd": "Console ProfileEnd Function",
        r"(?i)console\.memory": "Console Memory Access",
        r"(?i)console\.time": "Console Time Function",
        r"(?i)console\.timeEnd": "Console TimeEnd Function",
        r"(?i)console\.timeLog": "Console TimeLog Function",
        
        # Detect common JavaScript functions that can be abused
        r"(?i)(setTimeout|setInterval|Function|unescape)\s*\(": "Potentially Malicious JavaScript Functions",
        r"(?i)(new\s*Function)\s*\(": "Dynamic Function Creation",
        r"(?i)(window\.open|window\.close)\s*\(": "Window Open/Close Functions",
        r"(?i)document\.createElement\s*\(": "Document CreateElement Function",
        r"(?i)document\.createAttribute\s*\(": "Document CreateAttribute Function",
        r"(?i)document\.createTextNode\s*\(": "Document CreateTextNode Function",
        r"(?i)document\.createDocumentFragment\s*\(": "Document CreateDocumentFragment Function",
        r"(?i)document\.importNode\s*\(": "Document ImportNode Function",
        r"(?i)document\.getSelection\s*\(": "Document GetSelection Function",
        r"(?i)document\.execCommand\s*\(": "Document ExecCommand Function",
        r"(?i)document\.designMode\s*=\s*['\"]on['\"]": "Document DesignMode On",
        r"(?i)document\.body\.innerHTML\s*=": "Document Body InnerHTML Assignment",
        r"(?i)document\.head\.innerHTML\s*=": "Document Head InnerHTML Assignment",
        r"(?i)document\.title\s*=": "Document Title Assignment",
        r"(?i)document\.documentElement\.innerHTML\s*=": "Document Element InnerHTML Assignment",
        r"(?i)document\.cookie\s*=": "Document Cookie Assignment",
        r"(?i)localStorage\.setItem\s*\(": "LocalStorage SetItem Function",
        r"(?i)sessionStorage\.setItem\s*\(": "SessionStorage SetItem Function",
        r"(?i)indexedDB\.open\s*\(": "IndexedDB Open Function",
        r"(?i)WebAssembly\.compile\s*\(": "WebAssembly Compile Function",
        r"(?i)WebAssembly\.instantiate\s*\(": "WebAssembly Instantiate Function",
        
        # Common HTML entities that may lead to XSS
        r"(?i)&lt;": "HTML Entity for Less-Than (<)",
        r"(?i)&gt;": "HTML Entity for Greater-Than (>)",
        r"(?i)&quot;": "HTML Entity for Double Quote (\")",
        r"(?i)&apos;": "HTML Entity for Single Quote (')",
        r"(?i)&#x[a-fA-F0-9]{1,6};": "Hexadecimal HTML Entity",
        r"(?i)&#[0-9]{1,6};": "Decimal HTML Entity",
        r"(?i)&\w+;": "Named HTML Entity",
        r"(?i)&\#x[0-9A-Fa-f]{1,6};": "Hexadecimal HTML Entity with Hash",
        r"(?i)&\#[0-9]{1,6};": "Decimal HTML Entity with Hash",
        r"(?i)&\#x[0-9a-f]{1,6};": "Lowercase Hexadecimal HTML Entity with Hash",
        r"(?i)&\#x[A-F0-9]{1,6};": "Uppercase Hexadecimal HTML Entity with Hash",
        
        # Additional malicious XSS patterns
        r"(?i)<!--.*?-->": "HTML Comment Block",
        r"(?i)<\s*object\b[^>]*>": "Object Tag",
        r"(?i)<\s*applet\b[^>]*>": "Applet Tag",
        r"(?i)<\s*marquee\b[^>]*>": "Marquee Tag",
        r"(?i)<\s*blink\b[^>]*>": "Blink Tag",
        r"(?i)<\s*link\b[^>]*rel=['\"]?stylesheet['\"]?[^>]*>": "Link Tag with Stylesheet",
        r"(?i)<\s*meta\b[^>]*charset=['\"]?utf-7['\"]?[^>]*>": "Meta Charset UTF-7",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?content-type['\"]?[^>]*content=['\"]?text/html;\s*charset=windows-1256['\"]?[^>]*>": "Meta Content-Type with Charset Windows-1256",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?content-type['\"]?[^>]*content=['\"]?text/html;\s*charset=iso-8859-1['\"]?[^>]*>": "Meta Content-Type with Charset ISO-8859-1",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?content-type['\"]?[^>]*content=['\"]?text/html;\s*charset=shift_jis['\"]?[^>]*>": "Meta Content-Type with Charset Shift_JIS",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?content-type['\"]?[^>]*content=['\"]?text/html;\s*charset=gb2312['\"]?[^>]*>": "Meta Content-Type with Charset GB2312",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?content-type['\"]?[^>]*content=['\"]?text/html;\s*charset=euc-jp['\"]?[^>]*>": "Meta Content-Type with Charset EUC-JP",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?content-type['\"]?[^>]*content=['\"]?text/html;\s*charset=big5['\"]?[^>]*>": "Meta Content-Type with Charset BIG5",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?content-security-policy['\"]?[^>]*>": "Meta Content-Security-Policy",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?x-ua-compatible['\"]?[^>]*>": "Meta X-UA-Compatible",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?x-content-type-options['\"]?[^>]*>": "Meta X-Content-Type-Options",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?x-frame-options['\"]?[^>]*>": "Meta X-Frame-Options",
        r"(?i)<\s*meta\b[^>]*http-equiv=['\"]?x-xss-protection['\"]?[^>]*>": "Meta X-XSS-Protection",
        r"(?i)<\s*script\b[^>]*src=['\"]?data:[^>]*>": "Script Tag with Data URI",
        r"(?i)<\s*script\b[^>]*type=['\"]?text\/javascript['\"]?[^>]*>": "Script Tag with JavaScript Type",
        r"(?i)<\s*script\b[^>]*type=['\"]?application\/javascript['\"]?[^>]*>": "Script Tag with Application JavaScript Type",
        r"(?i)<\s*script\b[^>]*type=['\"]?text\/vbscript['\"]?[^>]*>": "Script Tag with VBScript Type",
        r"(?i)<\s*script\b[^>]*type=['\"]?application\/vbscript['\"]?[^>]*>": "Script Tag with Application VBScript Type",
        r"(?i)<\s*script\b[^>]*language=['\"]?javascript['\"]?[^>]*>": "Script Tag with JavaScript Language",
        r"(?i)<\s*script\b[^>]*language=['\"]?vbscript['\"]?[^>]*>": "Script Tag with VBScript Language",
        r"(?i)<\s*noscript\b[^>]*>": "Noscript Tag",
        r"(?i)<\s*template\b[^>]*>": "Template Tag",
        r"(?i)<\s*math\b[^>]*>": "Math Tag",
        r"(?i)<\s*plaintext\b[^>]*>": "Plaintext Tag",
        r"(?i)<\s*textarea\b[^>]*>": "Textarea Tag",
        r"(?i)<\s*select\b[^>]*>": "Select Tag",
        r"(?i)<\s*option\b[^>]*>": "Option Tag",
        r"(?i)<\s*textarea\b[^>]*on\w+=['\"].*?['\"]": "Textarea Tag with Event Handler",
        r"(?i)<\s*select\b[^>]*on\w+=['\"].*?['\"]": "Select Tag with Event Handler",
        r"(?i)<\s*option\b[^>]*on\w+=['\"].*?['\"]": "Option Tag with Event Handler",
        r"(?i)<\s*datalist\b[^>]*>": "Datalist Tag",
        r"(?i)<\s*output\b[^>]*>": "Output Tag",
        r"(?i)<\s*progress\b[^>]*>": "Progress Tag",
        r"(?i)<\s*meter\b[^>]*>": "Meter Tag",
        r"(?i)<\s*details\b[^>]*>": "Details Tag",
        r"(?i)<\s*summary\b[^>]*>": "Summary Tag",
        r"(?i)<\s*dialog\b[^>]*>": "Dialog Tag",
        r"(?i)<\s*embed\b[^>]*type=['\"]?application\/x-shockwave-flash['\"]?[^>]*>": "Embed Tag with Flash",
        r"(?i)<\s*embed\b[^>]*type=['\"]?application\/java-archive['\"]?[^>]*>": "Embed Tag with Java Archive",
        r"(?i)<\s*embed\b[^>]*type=['\"]?application\/pdf['\"]?[^>]*>": "Embed Tag with PDF",
        r"(?i)<\s*embed\b[^>]*type=['\"]?application\/xml['\"]?[^>]*>": "Embed Tag with XML",
        r"(?i)<\s*embed\b[^>]*type=['\"]?text\/html['\"]?[^>]*>": "Embed Tag with HTML",
        r"(?i)<\s*embed\b[^>]*type=['\"]?image\/svg\+xml['\"]?[^>]*>": "Embed Tag with SVG XML",
        r"(?i)<\s*embed\b[^>]*type=['\"]?video\/mp4['\"]?[^>]*>": "Embed Tag with MP4 Video",
        r"(?i)<\s*embed\b[^>]*type=['\"]?audio\/mp3['\"]?[^>]*>": "Embed Tag with MP3 Audio",
        
        # More JavaScript properties and methods
        r"(?i)document\.body\.innerHTML": "Document Body InnerHTML Access",
        r"(?i)document\.head\.innerHTML": "Document Head InnerHTML Access",
        r"(?i)document\.title": "Document Title Access",
        r"(?i)document\.documentElement\.innerHTML": "Document Element InnerHTML Access",
        r"(?i)window\.document\.innerHTML": "Window Document InnerHTML Access",
        r"(?i)window\.document\.body\.innerHTML": "Window Document Body InnerHTML Access",
        r"(?i)window\.document\.head\.innerHTML": "Window Document Head InnerHTML Access",
        r"(?i)window\.document\.title": "Window Document Title Access",
        r"(?i)window\.document\.documentElement\.innerHTML": "Window Document Element InnerHTML Access",
        r"(?i)window\.document\.cookie": "Window Document Cookie Access",
        r"(?i)window\.localStorage\.setItem": "Window LocalStorage SetItem Function",
        r"(?i)window\.localStorage\.getItem": "Window LocalStorage GetItem Function",
        r"(?i)window\.sessionStorage\.setItem": "Window SessionStorage SetItem Function",
        r"(?i)window\.sessionStorage\.getItem": "Window SessionStorage GetItem Function",
        r"(?i)window\.indexedDB\.open": "Window IndexedDB Open Function",
        r"(?i)window\.WebAssembly\.compile": "Window WebAssembly Compile Function",
        r"(?i)window\.WebAssembly\.instantiate": "Window WebAssembly Instantiate Function",
        r"(?i)window\.Worker\.": "Window Worker Object",
        r"(?i)window\.SharedWorker\.": "Window SharedWorker Object",
        r"(?i)window\.importScripts\(": "Window importScripts Function",
        r"(?i)window\.navigator\.userAgent": "Window Navigator UserAgent Access",
        r"(?i)window\.navigator\.platform": "Window Navigator Platform Access",
        r"(?i)window\.navigator\.appVersion": "Window Navigator AppVersion Access",
        r"(?i)window\.navigator\.appName": "Window Navigator AppName Access",
        r"(?i)window\.navigator\.language": "Window Navigator Language Access",
        r"(?i)window\.navigator\.languages": "Window Navigator Languages Access",
        r"(?i)window\.navigator\.geolocation": "Window Navigator Geolocation Access",
        r"(?i)window\.navigator\.permissions": "Window Navigator Permissions Access",
        r"(?i)window\.location\.hostname": "Window Location Hostname Access",
        r"(?i)window\.location\.pathname": "Window Location Pathname Access",
        r"(?i)window\.location\.search": "Window Location Search Access",
        r"(?i)window\.location\.hash": "Window Location Hash Access",
        r"(?i)window\.history\.pushState": "Window History PushState Function",
        r"(?i)window\.history\.replaceState": "Window History ReplaceState Function",
        r"(?i)window\.history\.back": "Window History Back Function",
        r"(?i)window\.history\.forward": "Window History Forward Function",
        r"(?i)window\.history\.go": "Window History Go Function",
        r"(?i)window\.console\.log": "Window Console Log Function",
        r"(?i)window\.console\.error": "Window Console Error Function",
        r"(?i)window\.console\.warn": "Window Console Warn Function",
        r"(?i)window\.console\.info": "Window Console Info Function",
        r"(?i)window\.console\.debug": "Window Console Debug Function",
        r"(?i)window\.console\.trace": "Window Console Trace Function",
        r"(?i)window\.console\.dir": "Window Console Dir Function",
        r"(?i)window\.console\.dirxml": "Window Console DirXML Function",
        r"(?i)window\.console\.table": "Window Console Table Function",
        r"(?i)window\.console\.group": "Window Console Group Function",
        r"(?i)window\.console\.groupEnd": "Window Console GroupEnd Function",
        r"(?i)window\.console\.clear": "Window Console Clear Function",
        r"(?i)window\.console\.count": "Window Console Count Function",
        r"(?i)window\.console\.assert": "Window Console Assert Function",
        r"(?i)window\.console\.profile": "Window Console Profile Function",
        r"(?i)window\.console\.profileEnd": "Window Console ProfileEnd Function",
        r"(?i)window\.console\.memory": "Window Console Memory Access",
        r"(?i)window\.console\.time": "Window Console Time Function",
        r"(?i)window\.console\.timeEnd": "Window Console TimeEnd Function",
        r"(?i)window\.console\.timeLog": "Window Console TimeLog Function",
        r"(?i)window\.document\.write": "Window Document Write Function",
        r"(?i)window\.document\.writeln": "Window Document Writeln Function",
        
        # Additional JavaScript injection patterns
        r"(?i)document\.body\.innerText": "Document Body InnerText Access",
        r"(?i)document\.body\.textContent": "Document Body TextContent Access",
        r"(?i)document\.head\.innerText": "Document Head InnerText Access",
        r"(?i)document\.head\.textContent": "Document Head TextContent Access",
        r"(?i)document\.documentElement\.innerText": "Document Element InnerText Access",
        r"(?i)document\.documentElement\.textContent": "Document Element TextContent Access",
        r"(?i)window\.document\.innerText": "Window Document InnerText Access",
        r"(?i)window\.document\.textContent": "Window Document TextContent Access",
        r"(?i)window\.document\.body\.innerText": "Window Document Body InnerText Access",
        r"(?i)window\.document\.body\.textContent": "Window Document Body TextContent Access",
        r"(?i)window\.document\.head\.innerText": "Window Document Head InnerText Access",
        r"(?i)window\.document\.head\.textContent": "Window Document Head TextContent Access",
        r"(?i)window\.document\.documentElement\.innerText": "Window Document Element InnerText Access",
        r"(?i)window\.document\.documentElement\.textContent": "Window Document Element TextContent Access",
        
        # Additional DOM manipulation patterns
        r"(?i)document\.createRange": "Document CreateRange Function",
        r"(?i)document\.createNodeIterator": "Document CreateNodeIterator Function",
        r"(?i)document\.createTreeWalker": "Document CreateTreeWalker Function",
        r"(?i)document\.getElementsByClassName": "getElementsByClassName Function",
        r"(?i)document\.getElementsByName": "getElementsByName Function",
        r"(?i)document\.querySelector\.all": "querySelectorAll Function",
        r"(?i)document\.querySelector\.all": "querySelectorAll Function",
        r"(?i)document\.evaluate": "Document Evaluate Function",
        r"(?i)document\.implementation\.createHTMLDocument": "Document Implementation CreateHTMLDocument Function",
        r"(?i)document\.implementation\.createDocument": "Document Implementation CreateDocument Function",
        r"(?i)document\.implementation\.createDocumentType": "Document Implementation CreateDocumentType Function",
        r"(?i)document\.implementation\.createElementNS": "Document Implementation CreateElementNS Function",
        r"(?i)document\.implementation\.createDocumentFragment": "Document Implementation CreateDocumentFragment Function",
        r"(?i)document\.importNode": "Document ImportNode Function",
        r"(?i)document\.adoptNode": "Document AdoptNode Function",
        r"(?i)document\.getElementById\.constructor": "Document GetElementById Constructor",
        
        # Other advanced XSS vectors
        r"(?i)<\s*script\b[^>]*>[^<]*<\/\s*script\s*>": "Empty Script Tag",
        r"(?i)<\s*script\b[^>]*>[^<]*<\/\s*script\s*>": "Script Tag with Content",
        r"(?i)<\s*script\b[^>]*>.*?<\/\s*script\s*>": "Script Tag with Any Content",
        r"(?i)<\s*script\b[^>]*>.*?<\/\s*script\s*>": "Script Tag with Any Content",
        r"(?i)<\s*script\b[^>]*>.*?<\/\s*script\s*>": "Script Tag with Any Content",
        r"(?i)<\s*script\b[^>]*>.*?<\/\s*script\s*>": "Script Tag with Any Content",
        # ... Repeat similar patterns as needed
        
        # Additional function patterns
        r"(?i)document\.getElementById\s*\(": "Document GetElementById Function",
        r"(?i)document\.getElementsByClassName\s*\(": "Document GetElementsByClassName Function",
        r"(?i)document\.getElementsByTagName\s*\(": "Document GetElementsByTagName Function",
        r"(?i)document\.querySelector\s*\(": "Document QuerySelector Function",
        r"(?i)document\.querySelectorAll\s*\(": "Document QuerySelectorAll Function",
        r"(?i)document\.createElement\s*\(": "Document CreateElement Function",
        r"(?i)document\.createTextNode\s*\(": "Document CreateTextNode Function",
        r"(?i)document\.createAttribute\s*\(": "Document CreateAttribute Function",
        r"(?i)document\.createComment\s*\(": "Document CreateComment Function",
        r"(?i)document\.importNode\s*\(": "Document ImportNode Function",
        r"(?i)document\.adoptNode\s*\(": "Document AdoptNode Function",
        r"(?i)document\.createDocumentFragment\s*\(": "Document CreateDocumentFragment Function",
        r"(?i)document\.createRange\s*\(": "Document CreateRange Function",
        r"(?i)document\.execCommand\s*\(": "Document ExecCommand Function",
        r"(?i)document\.write\s*\(": "Document Write Function",
        r"(?i)document\.writeln\s*\(": "Document Writeln Function",
        r"(?i)document\.designMode\s*=\s*['\"]on['\"]": "Document DesignMode On",
        r"(?i)document\.location\s*=": "Document Location Assignment",
        r"(?i)document\.referrer\s*=": "Document Referrer Assignment",
        r"(?i)document\.lastModified\s*=": "Document Last Modified Assignment",
        r"(?i)navigator\.userAgent\s*=": "Navigator UserAgent Assignment",
        r"(?i)navigator\.platform\s*=": "Navigator Platform Assignment",
        r"(?i)navigator\.appVersion\s*=": "Navigator AppVersion Assignment",
        r"(?i)navigator\.appName\s*=": "Navigator AppName Assignment",
        r"(?i)navigator\.language\s*=": "Navigator Language Assignment",
        r"(?i)navigator\.languages\s*=": "Navigator Languages Assignment",
        r"(?i)navigator\.geolocation\.getCurrentPosition\s*\(": "Navigator Geolocation GetCurrentPosition Function",
        r"(?i)navigator\.permissions\.query\s*\(": "Navigator Permissions Query Function",
        r"(?i)location\.href\s*=": "Location Href Assignment",
        r"(?i)location\.assign\s*\(": "Location Assign Function",
        r"(?i)location\.replace\s*\(": "Location Replace Function",
        r"(?i)location\.reload\s*\(": "Location Reload Function",
        r"(?i)history\.pushState\s*\(": "History PushState Function",
        r"(?i)history\.replaceState\s*\(": "History ReplaceState Function",
        r"(?i)history\.back\s*\(": "History Back Function",
        r"(?i)history\.forward\s*\(": "History Forward Function",
        r"(?i)history\.go\s*\(": "History Go Function",
        r"(?i)console\.log\s*\(": "Console Log Function",
        r"(?i)console\.error\s*\(": "Console Error Function",
        r"(?i)console\.warn\s*\(": "Console Warn Function",
        r"(?i)console\.info\s*\(": "Console Info Function",
        r"(?i)console\.debug\s*\(": "Console Debug Function",
        r"(?i)console\.trace\s*\(": "Console Trace Function",
        r"(?i)console\.dir\s*\(": "Console Dir Function",
        r"(?i)console\.dirxml\s*\(": "Console DirXML Function",
        r"(?i)console\.table\s*\(": "Console Table Function",
        r"(?i)console\.group\s*\(": "Console Group Function",
        r"(?i)console\.groupEnd\s*\(": "Console GroupEnd Function",
        r"(?i)console\.clear\s*\(": "Console Clear Function",
        r"(?i)console\.count\s*\(": "Console Count Function",
        r"(?i)console\.assert\s*\(": "Console Assert Function",
        r"(?i)console\.profile\s*\(": "Console Profile Function",
        r"(?i)console\.profileEnd\s*\(": "Console ProfileEnd Function",
        r"(?i)console\.memory\s*\(": "Console Memory Access Function",
        r"(?i)console\.time\s*\(": "Console Time Function",
        r"(?i)console\.timeEnd\s*\(": "Console TimeEnd Function",
        r"(?i)console\.timeLog\s*\(": "Console TimeLog Function",
        r"(?i)window\.console\.log\s*\(": "Window Console Log Function",
        r"(?i)window\.console\.error\s*\(": "Window Console Error Function",
        r"(?i)window\.console\.warn\s*\(": "Window Console Warn Function",
        r"(?i)window\.console\.info\s*\(": "Window Console Info Function",
        r"(?i)window\.console\.debug\s*\(": "Window Console Debug Function",
        r"(?i)window\.console\.trace\s*\(": "Window Console Trace Function",
        r"(?i)window\.console\.dir\s*\(": "Window Console Dir Function",
        r"(?i)window\.console\.dirxml\s*\(": "Window Console DirXML Function",
        r"(?i)window\.console\.table\s*\(": "Window Console Table Function",
        r"(?i)window\.console\.group\s*\(": "Window Console Group Function",
        r"(?i)window\.console\.groupEnd\s*\(": "Window Console GroupEnd Function",
        r"(?i)window\.console\.clear\s*\(": "Window Console Clear Function",
        r"(?i)window\.console\.count\s*\(": "Window Console Count Function",
        r"(?i)window\.console\.assert\s*\(": "Window Console Assert Function",
        r"(?i)window\.console\.profile\s*\(": "Window Console Profile Function",
        r"(?i)window\.console\.profileEnd\s*\(": "Window Console ProfileEnd Function",
        r"(?i)window\.console\.memory\s*\(": "Window Console Memory Access Function",
        r"(?i)window\.console\.time\s*\(": "Window Console Time Function",
        r"(?i)window\.console\.timeEnd\s*\(": "Window Console TimeEnd Function",
        r"(?i)window\.console\.timeLog\s*\(": "Window Console TimeLog Function",
        
        # JavaScript frameworks and libraries
        r"(?i)jQuery\.": "jQuery Object",
        r"(?i)React\.": "React Library",
        r"(?i)Angular\.": "Angular Framework",
        r"(?i)Vue\.": "Vue.js Framework",
        r"(?i)Ember\.": "Ember.js Framework",
        r"(?i)Backbone\.": "Backbone.js Framework",
        r"(?i)D3\.": "D3.js Library",
        r"(?i)Lodash\.": "Lodash Library",
        r"(?i)Underscore\.": "Underscore.js Library",
        r"(?i)Handlebars\.": "Handlebars.js Library",
        r"(?i)Mustache\.": "Mustache.js Library",
        r"(?i)Knockout\.": "Knockout.js Library",
        r"(?i)Ext\.": "Ext JS Library",
        r"(?i)Backbone\.View": "Backbone View",
        r"(?i)ReactDOM\.render": "ReactDOM Render Function",
        r"(?i)Vue\.prototype\.": "Vue Prototype",
        r"(?i)Angular\.module": "Angular Module",
        r"(?i)Ember\.component": "Ember Component",
        
        # Template Injection Patterns
        r"(?i)\{\{.*?\}\}": "Handlebars/Mustache Template",
        r"(?i)\<%\s*.*?\s*%>": "ERB/ASP Template",
        r"(?i)\${.*?}": "ES6 Template Literal",
        r"(?i)\{\%\s*.*?\s*\%\}": "Django/Flask Template",
        r"(?i)\[\[.*?\]\]": "AngularJS Template",
        r"(?i)\{\#.*?\#\}": "Liquid Template",
        r"(?i)\{\{!\s*.*?\}\}": "Handlebars Comment",
        r"(?i)<\s*%.*?%>": "ASP.NET Inline Code",
        
        # JSON-based XSS patterns
        r"(?i)\"\s*\+\s*\"": "JSON String Concatenation",
        r"(?i)\{\s*\"[^\"\}]+\s*\"\s*:\s*\"[^\"\}]+\"\s*\}": "Simple JSON Object",
        r"(?i)\[\s*\".*?\"\s*\]": "JSON Array",
        
        # Data URIs
        r"(?i)data:text\/html": "Data URI with Text/HTML",
        r"(?i)data:text\/javascript": "Data URI with Text/JavaScript",
        r"(?i)data:application\/javascript": "Data URI with Application/JavaScript",
        r"(?i)data:image\/svg\+xml": "Data URI with Image/SVG+xml",
        r"(?i)data:application\/x-shockwave-flash": "Data URI with Flash",
        
        # Miscellaneous patterns
        r"(?i)\bjavascript\s*:\s*": "JavaScript Protocol with Spaces",
        r"(?i)\bdata\s*:\s*text\/html": "Data Protocol with Text/HTML",
        r"(?i)\bdata\s*:\s*application\/javascript": "Data Protocol with Application/JavaScript",
        r"(?i)\bdata\s*:\s*image\/svg\+xml": "Data Protocol with Image/SVG+xml",
        r"(?i)\bdata\s*:\s*application\/x-shockwave-flash": "Data Protocol with Flash",
        r"(?i)\babout\s*:\s*blank": "About Protocol Blank",
        r"(?i)\bblob\s*:\s*": "Blob Protocol",
        r"(?i)\bfilesystem\s*:\s*": "Filesystem Protocol",
        r"(?i)\bms-application\s*:\s*": "MS Application Protocol",
        r"(?i)\bmailto\s*:\s*": "Mailto Protocol",
        r"(?i)\btel\s*:\s*": "Tel Protocol",
        r"(?i)\btelnet\s*:\s*": "Telnet Protocol",
        r"(?i)\bfirefox\s*:\s*": "Firefox Protocol",
        r"(?i)\bchrome\s*:\s*": "Chrome Protocol",
        r"(?i)\bopera\s*:\s*": "Opera Protocol",
        r"(?i)\belectron\s*:\s*": "Electron Protocol",
        
        # Protocol-relative URLs
        r"(?i)//.*?": "Protocol-relative URL",
        
        # Encoded protocols
        r"(?i)\/\/.*?": "Double Slash Protocol-relative URL",
        r"(?i)\/\*.*?\*\/\/\/.*?": "Obfuscated Protocol-relative URL",
        
        # Special characters
        r"(?i)[<>\"'`{}|\\^~\[\]`<>]": "Special Characters in Payload",
        r"(?i)\b<script\b": "Script Tag Start Word Boundary",
        r"(?i)\b<script\b[^>]*>": "Script Tag with Attributes",
        r"(?i)\b</script>": "Script Tag Closing",
        r"(?i)\b</script\b[^>]*>": "Script Tag Closing with Attributes",
        r"(?i)\b<iframe\b[^>]*>": "Iframe Tag with Attributes",
        r"(?i)\b<\/iframe>": "Iframe Tag Closing",
        r"(?i)\b<svg\b[^>]*>": "SVG Tag with Attributes",
        r"(?i)\b<\/svg>": "SVG Tag Closing",
        r"(?i)\b<embed\b[^>]*>": "Embed Tag with Attributes",
        r"(?i)\b<\/embed>": "Embed Tag Closing",
        r"(?i)\b<object\b[^>]*>": "Object Tag with Attributes",
        r"(?i)\b<\/object>": "Object Tag Closing",
        r"(?i)\b<applet\b[^>]*>": "Applet Tag with Attributes",
        r"(?i)\b<\/applet>": "Applet Tag Closing",
        r"(?i)\b<form\b[^>]*>": "Form Tag with Attributes",
        r"(?i)\b<\/form>": "Form Tag Closing",
        r"(?i)\b<base\b[^>]*>": "Base Tag with Attributes",
        r"(?i)\b<\/base>": "Base Tag Closing",
        
        # Event handler variations
        r"(?i)onabort\s*=\s*['\"].*?['\"]": "Onabort Event Handler",
        r"(?i)oncanplay\s*=\s*['\"].*?['\"]": "Oncanplay Event Handler",
        r"(?i)oncanplaythrough\s*=\s*['\"].*?['\"]": "Oncanplaythrough Event Handler",
        r"(?i)onchange\s*=\s*['\"].*?['\"]": "Onchange Event Handler",
        r"(?i)oncontextmenu\s*=\s*['\"].*?['\"]": "Oncontextmenu Event Handler",
        r"(?i)ondrag\s*=\s*['\"].*?['\"]": "Ondrag Event Handler",
        r"(?i)ondragend\s*=\s*['\"].*?['\"]": "Ondragend Event Handler",
        r"(?i)ondragenter\s*=\s*['\"].*?['\"]": "Ondragenter Event Handler",
        r"(?i)ondragleave\s*=\s*['\"].*?['\"]": "Ondragleave Event Handler",
        r"(?i)ondragover\s*=\s*['\"].*?['\"]": "Ondragover Event Handler",
        r"(?i)ondragstart\s*=\s*['\"].*?['\"]": "Ondragstart Event Handler",
        r"(?i)ondrop\s*=\s*['\"].*?['\"]": "Ondrop Event Handler",
        r"(?i)onerror\s*=\s*['\"].*?['\"]": "Onerror Event Handler",
        r"(?i)onfocus\s*=\s*['\"].*?['\"]": "Onfocus Event Handler",
        r"(?i)oninput\s*=\s*['\"].*?['\"]": "Oninput Event Handler",
        r"(?i)oninvalid\s*=\s*['\"].*?['\"]": "Oninvalid Event Handler",
        r"(?i)onkeydown\s*=\s*['\"].*?['\"]": "Onkeydown Event Handler",
        r"(?i)onkeypress\s*=\s*['\"].*?['\"]": "Onkeypress Event Handler",
        r"(?i)onkeyup\s*=\s*['\"].*?['\"]": "Onkeyup Event Handler",
        r"(?i)onload\s*=\s*['\"].*?['\"]": "Onload Event Handler",
        r"(?i)onloadeddata\s*=\s*['\"].*?['\"]": "Onloadeddata Event Handler",
        r"(?i)onloadedmetadata\s*=\s*['\"].*?['\"]": "Onloadedmetadata Event Handler",
        r"(?i)onloadstart\s*=\s*['\"].*?['\"]": "Onloadstart Event Handler",
        r"(?i)onmousedown\s*=\s*['\"].*?['\"]": "Onmousedown Event Handler",
        r"(?i)onmousemove\s*=\s*['\"].*?['\"]": "Onmousemove Event Handler",
        r"(?i)onmouseout\s*=\s*['\"].*?['\"]": "Onmouseout Event Handler",
        r"(?i)onmouseover\s*=\s*['\"].*?['\"]": "Onmouseover Event Handler",
        r"(?i)onmouseup\s*=\s*['\"].*?['\"]": "Onmouseup Event Handler",
        r"(?i)onmousewheel\s*=\s*['\"].*?['\"]": "Onmousewheel Event Handler",
        r"(?i)onpause\s*=\s*['\"].*?['\"]": "Onpause Event Handler",
        r"(?i)onplay\s*=\s*['\"].*?['\"]": "Onplay Event Handler",
        r"(?i)onplaying\s*=\s*['\"].*?['\"]": "Onplaying Event Handler",
        r"(?i)onprogress\s*=\s*['\"].*?['\"]": "Onprogress Event Handler",
        r"(?i)onratechange\s*=\s*['\"].*?['\"]": "Onratechange Event Handler",
        r"(?i)onreset\s*=\s*['\"].*?['\"]": "Onreset Event Handler",
        r"(?i)onresize\s*=\s*['\"].*?['\"]": "Onresize Event Handler",
        r"(?i)onscroll\s*=\s*['\"].*?['\"]": "Onscroll Event Handler",
        r"(?i)onseeked\s*=\s*['\"].*?['\"]": "Onseeked Event Handler",
        r"(?i)onseeking\s*=\s*['\"].*?['\"]": "Onseeking Event Handler",
        r"(?i)onselect\s*=\s*['\"].*?['\"]": "Onselect Event Handler",
        r"(?i)onshow\s*=\s*['\"].*?['\"]": "Onshow Event Handler",
        r"(?i)onstalled\s*=\s*['\"].*?['\"]": "Onstalled Event Handler",
        r"(?i)onsubmit\s*=\s*['\"].*?['\"]": "Onsubmit Event Handler",
        r"(?i)onsuspend\s*=\s*['\"].*?['\"]": "Onsuspend Event Handler",
        r"(?i)ontimeupdate\s*=\s*['\"].*?['\"]": "Ontimeupdate Event Handler",
        r"(?i)ontoggle\s*=\s*['\"].*?['\"]": "Ontoggle Event Handler",
        r"(?i)onvolumechange\s*=\s*['\"].*?['\"]": "Onvolumechange Event Handler",
        r"(?i)onwaiting\s*=\s*['\"].*?['\"]": "Onwaiting Event Handler",
        r"(?i)onwheel\s*=\s*['\"].*?['\"]": "Onwheel Event Handler",
        r"(?i)ontouchstart\s*=\s*['\"].*?['\"]": "Ontouchstart Event Handler",
        r"(?i)ontouchend\s*=\s*['\"].*?['\"]": "Ontouchend Event Handler",
        r"(?i)ontouchmove\s*=\s*['\"].*?['\"]": "Ontouchmove Event Handler",
        r"(?i)ontouchcancel\s*=\s*['\"].*?['\"]": "Ontouchcancel Event Handler",
        
        # Additional protocol patterns
        r"(?i)\bftp\s*:\s*": "FTP Protocol",
        r"(?i)\bssh\s*:\s*": "SSH Protocol",
        r"(?i)\bsftp\s*:\s*": "SFTP Protocol",
        r"(?i)\btftp\s*:\s*": "TFTP Protocol",
        r"(?i)\bldap\s*:\s*": "LDAP Protocol",
        r"(?i)\bnews\s*:\s*": "News Protocol",
        r"(?i)\bmailto\s*:\s*": "Mailto Protocol",
        r"(?i)\btel\s*:\s*": "Tel Protocol",
        r"(?i)\btelnet\s*:\s*": "Telnet Protocol",
        r"(?i)\bfile\s*:\s*": "File Protocol",
        r"(?i)\bdata\s*:\s*": "Data Protocol",
        r"(?i)\bblob\s*:\s*": "Blob Protocol",
        r"(?i)\bfilesystem\s*:\s*": "Filesystem Protocol",
        r"(?i)\bms-application\s*:\s*": "MS Application Protocol",
        r"(?i)\belectron\s*:\s*": "Electron Protocol",
        r"(?i)\bchrome\s*:\s*": "Chrome Protocol",
        r"(?i)\bfirefox\s*:\s*": "Firefox Protocol",
        r"(?i)\bopera\s*:\s*": "Opera Protocol",
        r"(?i)\bedge\s*:\s*": "Edge Protocol",
        r"(?i)\byoutube\s*:\s*": "YouTube Protocol",
        r"(?i)\bgit\s*:\s*": "Git Protocol",
        r"(?i)\bsvn\s*:\s*": "SVN Protocol",
        r"(?i)\birc\s*:\s*": "IRC Protocol",
        r"(?i)\bsvn\s*:\s*": "SVN Protocol",
        r"(?i)\bssh\s*:\s*": "SSH Protocol",
        r"(?i)\bssh2\s*:\s*": "SSH2 Protocol",
        
        # SVG-specific XSS vectors
        r"(?i)<\s*svg\b[^>]*>": "SVG Tag",
        r"(?i)<\s*svg\b[^>]*xmlns=['\"]?http:\/\/www\.w3\.org\/2000\/svg['\"]?[^>]*>": "SVG Tag with Namespace",
        r"(?i)<\s*svg\b[^>]*>.*?<\s*script\b[^>]*>.*?<\/script>.*?<\s*\/svg>": "SVG with Embedded Script",
        r"(?i)<\s*svg\b[^>]*>.*?<\s*foreignObject\b[^>]*>.*?<\s*script\b[^>]*>.*?<\/script>.*?<\s*\/foreignObject>.*?<\s*\/svg>": "SVG with ForeignObject and Script",
        r"(?i)<\s*svg\b[^>]*>.*?<\s*animate\b[^>]*>.*?<\s*script\b[^>]*>.*?<\/script>.*?<\s*\/animate>.*?<\s*\/svg>": "SVG with Animate and Script",
        r"(?i)<\s*svg\b[^>]*>.*?<\s*style\b[^>]*>.*?expression\([^)]*\).*?<\s*\/style>.*?<\s*\/svg>": "SVG with Style Expression",
        
        # HTML5-specific XSS vectors
        r"(?i)<\s*video\b[^>]*>": "Video Tag",
        r"(?i)<\s*audio\b[^>]*>": "Audio Tag",
        r"(?i)<\s*canvas\b[^>]*>": "Canvas Tag",
        r"(?i)<\s*details\b[^>]*>": "Details Tag",
        r"(?i)<\s*summary\b[^>]*>": "Summary Tag",
        r"(?i)<\s*dialog\b[^>]*>": "Dialog Tag",
        r"(?i)<\s*template\b[^>]*>": "Template Tag",
        r"(?i)<\s*meter\b[^>]*>": "Meter Tag",
        r"(?i)<\s*progress\b[^>]*>": "Progress Tag",
        r"(?i)<\s*datalist\b[^>]*>": "Datalist Tag",
        r"(?i)<\s*output\b[^>]*>": "Output Tag",
        
        # Miscellaneous malicious patterns
        r"(?i)window\.sessionStorage\.setItem\s*\(": "Window SessionStorage SetItem Function",
        r"(?i)window\.localStorage\.setItem\s*\(": "Window LocalStorage SetItem Function",
        r"(?i)document\.currentScript": "Document CurrentScript Property",
        r"(?i)document\.defaultView": "Document DefaultView Property",
        r"(?i)document\.documentURI": "Document DocumentURI Property",
        r"(?i)window\.document\.URL": "Window Document URL Access",
        r"(?i)window\.document\.documentURI": "Window Document DocumentURI Access",
        r"(?i)window\.document\.defaultView": "Window Document DefaultView Access",
        r"(?i)document\.URL": "Document URL Property",
        r"(?i)document\.documentURI": "Document DocumentURI Property",
        r"(?i)document\.referrer": "Document Referrer Property",
        r"(?i)document\.cookie\s*=": "Document Cookie Assignment",
        r"(?i)window\.open\s*\(": "Window Open Function",
        r"(?i)window\.close\s*\(": "Window Close Function",
        r"(?i)window\.showModalDialog\s*\(": "Window showModalDialog Function",
        r"(?i)window\.alert\s*\(": "Window Alert Function",
        r"(?i)window\.prompt\s*\(": "Window Prompt Function",
        r"(?i)window\.confirm\s*\(": "Window Confirm Function",
        r"(?i)window\.print\s*\(": "Window Print Function",
        r"(?i)window\.execScript\s*\(": "Window execScript Function",
        r"(?i)window\.eval\s*\(": "Window eval Function",
        r"(?i)window\.setInterval\s*\(": "Window setInterval Function",
        r"(?i)window\.setTimeout\s*\(": "Window setTimeout Function",
        r"(?i)window\.Function\s*\(": "Window Function Constructor",
        r"(?i)window\.unescape\s*\(": "Window unescape Function",
        r"(?i)window\.escape\s*\(": "Window escape Function",
        r"(?i)window\.encodeURI\s*\(": "Window encodeURI Function",
        r"(?i)window\.encodeURIComponent\s*\(": "Window encodeURIComponent Function",
        r"(?i)window\.decodeURI\s*\(": "Window decodeURI Function",
        r"(?i)window\.decodeURIComponent\s*\(": "Window decodeURIComponent Function",
        r"(?i)window\.console\.log\s*\(": "Window Console Log Function",
        r"(?i)window\.console\.error\s*\(": "Window Console Error Function",
        r"(?i)window\.console\.warn\s*\(": "Window Console Warn Function",
        r"(?i)window\.console\.info\s*\(": "Window Console Info Function",
        r"(?i)window\.console\.debug\s*\(": "Window Console Debug Function",
        r"(?i)window\.console\.trace\s*\(": "Window Console Trace Function",
        r"(?i)window\.console\.dir\s*\(": "Window Console Dir Function",
        r"(?i)window\.console\.dirxml\s*\(": "Window Console DirXML Function",
        r"(?i)window\.console\.table\s*\(": "Window Console Table Function",
        r"(?i)window\.console\.group\s*\(": "Window Console Group Function",
        r"(?i)window\.console\.groupEnd\s*\(": "Window Console GroupEnd Function",
        r"(?i)window\.console\.clear\s*\(": "Window Console Clear Function",
        r"(?i)window\.console\.count\s*\(": "Window Console Count Function",
        r"(?i)window\.console\.assert\s*\(": "Window Console Assert Function",
        r"(?i)window\.console\.profile\s*\(": "Window Console Profile Function",
        r"(?i)window\.console\.profileEnd\s*\(": "Window Console ProfileEnd Function",
        r"(?i)window\.console\.memory\s*\(": "Window Console Memory Access Function",
        r"(?i)window\.console\.time\s*\(": "Window Console Time Function",
        r"(?i)window\.console\.timeEnd\s*\(": "Window Console TimeEnd Function",
        r"(?i)window\.console\.timeLog\s*\(": "Window Console TimeLog Function",
    }

    # Additional patterns can be added here following the same structure
    # For example:
    # r"your_new_regex_pattern_here": "Description of the new pattern",

    # Check for XSS patterns in both the encoded and decoded payload
    detected_patterns = []
    for pattern, description in xss_patterns.items():
        match_encoded = re.search(pattern, payload)
        match_decoded = re.search(pattern, decoded_payload)
        
        # If there is a match in either the encoded or decoded payload, add to results
        if match_encoded:
            detected_patterns.append((description, match_encoded.group(0)))
        elif match_decoded:
            detected_patterns.append((description, match_decoded.group(0)))
    
    # Return the detected patterns or None if no XSS is found
    if detected_patterns:
        return detected_patterns
    return None

def main():
    user_input = input(Fore.YELLOW + "Enter the URL or payload to check for XSS: " + Style.RESET_ALL)
    result = detect_xss_payload(user_input)
    if result:
        print(Fore.GREEN + f"\nPayload: {user_input}\n" + Style.RESET_ALL + "XSS Patterns Detected:")
        for description, matched_part in result:
            print(Fore.CYAN + f"- {description}: {matched_part}" + Style.RESET_ALL)
    else:
        print(Fore.RED + f"\nPayload: {user_input} - No XSS Detected\n" + Style.RESET_ALL)
