"""
Terralab: A CLI for the Terra Scientific Pipelines Service (Teaspoons).

This package provides a command-line interface to interact with the Teaspoons service,
built on top of an autogenerated thin client.
"""

__version__ = "0.0.1"
__author__ = "Terra Scientific Services"
__email__ = "teaspoons-developers@broadinstitute.org"
