def addf(a: float, b: float) -> float: ...
def addi(a: int, b: int) -> int: ...

def subf(a: float, b: float) -> float: ...
def subi(a: int, b: int) -> int: ...

def mulf(a: float, b: float) -> float: ...
def muli(a: int, b: int) -> int: ...

def truediv(a: float, b: float) -> float: ...
def floordiv(a: float, b: float) -> int: ...

def modulof(a: float, b: float) -> float: ...
def moduloi(a: int, b: int) -> int: ...

def powf(a: float, b: float) -> float: ...
def powi(a: int, b: int) -> int: ...

__all__ = [
    "addf", "addi",
    "subf", "subi",
    "mulf", "muli",
    "truediv", "floordiv",
    "modulof", "moduloi",
    "powf", "powi"
]
