# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/lidar/lib/detector/cnn_segmentation/proto/spp_engine_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nTmodules/perception/lidar/lib/detector/cnn_segmentation/proto/spp_engine_config.proto\x12\x17\x61pollo.perception.lidar\"*\n\x0fSppEngineConfig\x12\x17\n\nheight_gap\x18\x08 \x01(\x02:\x03\x30.5')



_SPPENGINECONFIG = DESCRIPTOR.message_types_by_name['SppEngineConfig']
SppEngineConfig = _reflection.GeneratedProtocolMessageType('SppEngineConfig', (_message.Message,), {
  'DESCRIPTOR' : _SPPENGINECONFIG,
  '__module__' : 'modules.perception.lidar.lib.detector.cnn_segmentation.proto.spp_engine_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.SppEngineConfig)
  })
_sym_db.RegisterMessage(SppEngineConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPPENGINECONFIG._serialized_start=113
  _SPPENGINECONFIG._serialized_end=155
# @@protoc_insertion_point(module_scope)
