# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/common_msgs/localization_msgs/pose.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_modules.modules.common_msgs.basic_msgs import geometry_pb2 as modules_dot_common__msgs_dot_basic__msgs_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0modules/common_msgs/localization_msgs/pose.proto\x12\x13\x61pollo.localization\x1a-modules/common_msgs/basic_msgs/geometry.proto\"\xa7\x03\n\x04Pose\x12)\n\x08position\x18\x01 \x01(\x0b\x32\x17.apollo.common.PointENU\x12.\n\x0borientation\x18\x02 \x01(\x0b\x32\x19.apollo.common.Quaternion\x12/\n\x0flinear_velocity\x18\x03 \x01(\x0b\x32\x16.apollo.common.Point3D\x12\x33\n\x13linear_acceleration\x18\x04 \x01(\x0b\x32\x16.apollo.common.Point3D\x12\x30\n\x10\x61ngular_velocity\x18\x05 \x01(\x0b\x32\x16.apollo.common.Point3D\x12\x0f\n\x07heading\x18\x06 \x01(\x01\x12\x37\n\x17linear_acceleration_vrf\x18\x07 \x01(\x0b\x32\x16.apollo.common.Point3D\x12\x34\n\x14\x61ngular_velocity_vrf\x18\x08 \x01(\x0b\x32\x16.apollo.common.Point3D\x12,\n\x0c\x65uler_angles\x18\t \x01(\x0b\x32\x16.apollo.common.Point3D')



_POSE = DESCRIPTOR.message_types_by_name['Pose']
Pose = _reflection.GeneratedProtocolMessageType('Pose', (_message.Message,), {
  'DESCRIPTOR' : _POSE,
  '__module__' : 'modules.common_msgs.localization_msgs.pose_pb2'
  # @@protoc_insertion_point(class_scope:apollo.localization.Pose)
  })
_sym_db.RegisterMessage(Pose)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSE._serialized_start=121
  _POSE._serialized_end=544
# @@protoc_insertion_point(module_scope)
