# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/planning_base/proto/plugin_declare_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>modules/planning/planning_base/proto/plugin_declare_info.proto\x12\x0f\x61pollo.planning\"/\n\x11PluginDeclareInfo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04type\x18\x02 \x02(\t')



_PLUGINDECLAREINFO = DESCRIPTOR.message_types_by_name['PluginDeclareInfo']
PluginDeclareInfo = _reflection.GeneratedProtocolMessageType('PluginDeclareInfo', (_message.Message,), {
  'DESCRIPTOR' : _PLUGINDECLAREINFO,
  '__module__' : 'modules.planning.planning_base.proto.plugin_declare_info_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.PluginDeclareInfo)
  })
_sym_db.RegisterMessage(PluginDeclareInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLUGINDECLAREINFO._serialized_start=83
  _PLUGINDECLAREINFO._serialized_end=130
# @@protoc_insertion_point(module_scope)
