from typing import overload
import java.lang


class MemorySearchOptions(object):
    """
    Class for managing search tool options.
    """





    @overload
    def __init__(self): ...

    @overload
    def __init__(self, tool: ghidra.framework.plugintool.PluginTool): ...



    def equals(self, __a0: object) -> bool: ...

    def getByteDelimiter(self) -> unicode: ...

    def getByteGroupSize(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getSearchLimit(self) -> int: ...

    def hashCode(self) -> int: ...

    def isAutoRestrictSelection(self) -> bool: ...

    def isShowHighlights(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def autoRestrictSelection(self) -> bool: ...

    @property
    def byteDelimiter(self) -> unicode: ...

    @property
    def byteGroupSize(self) -> int: ...

    @property
    def searchLimit(self) -> int: ...

    @property
    def showHighlights(self) -> bool: ...