"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import foxtail_trainer_client
from foxtail_trainer_client.model.prediction_status import PredictionStatus
globals()['PredictionStatus'] = PredictionStatus
from foxtail_trainer_client.model.update_data_set_chunk_status_command import UpdateDataSetChunkStatusCommand


class TestUpdateDataSetChunkStatusCommand(unittest.TestCase):
    """UpdateDataSetChunkStatusCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateDataSetChunkStatusCommand(self):
        """Test UpdateDataSetChunkStatusCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateDataSetChunkStatusCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
