"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import foxtail_trainer_client
from foxtail_trainer_client.model.create_ml_model_dto import CreateMLModelDto
globals()['CreateMLModelDto'] = CreateMLModelDto
from foxtail_trainer_client.model.create_ml_models_command import CreateMLModelsCommand


class TestCreateMLModelsCommand(unittest.TestCase):
    """CreateMLModelsCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateMLModelsCommand(self):
        """Test CreateMLModelsCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateMLModelsCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
