"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import foxtail_trainer_client
from foxtail_trainer_client.model.ml_models_guids_list_dto import MLModelsGuidsListDto


class TestMLModelsGuidsListDto(unittest.TestCase):
    """MLModelsGuidsListDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMLModelsGuidsListDto(self):
        """Test MLModelsGuidsListDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MLModelsGuidsListDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
