from typing import overload
import ghidra.framework.options
import ghidra.util
import java.awt
import java.beans
import java.lang


class ThemeFontOption(ghidra.framework.options.Option):
    """
    Options implementation for theme font options. A ThemeFontOption is an option that, when
     changed, affects the current theme and is saved in the theme, instead of being saved with
     normal non-theme related options.
    """





    def __init__(self, optionName: unicode, fontId: unicode, description: unicode, help: ghidra.util.HelpLocation): ...



    def doSetCurrentValue(self, value: object) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCurrentValue(self) -> java.awt.Font: ...

    def getDefaultValue(self) -> object: ...

    def getDescription(self) -> unicode: ...

    def getHelpLocation(self) -> ghidra.util.HelpLocation: ...

    def getInceptionInformation(self) -> unicode: ...

    def getName(self) -> unicode: ...

    def getOptionType(self) -> ghidra.framework.options.OptionType: ...

    def getPropertyEditor(self) -> java.beans.PropertyEditor: ...

    def getValue(self, passedInDefaultValue: object) -> object: ...

    def hashCode(self) -> int: ...

    def isDefault(self) -> bool: ...

    def isRegistered(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def restoreDefault(self) -> None: ...

    def setCurrentValue(self, value: object) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def currentValue(self) -> java.awt.Font: ...

    @property
    def default(self) -> bool: ...

    @property
    def defaultValue(self) -> object: ...