# Generated by Django 5.1 on 2024-08-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sitewide", "0002_terms_delete_setting_terms_unique_phrase"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Terms",
            new_name="Phrase",
        ),
        migrations.AlterModelTable(
            name="phrase",
            table="phrase",
        ),
    ]
