# Generated by Django 5.1 on 2024-08-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitewide", "0003_rename_terms_phrase_alter_phrase_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("niche", models.CharField(max_length=255)),
                ("phrase", models.CharField(max_length=255)),
                ("rephrase", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "term",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="Phrase",
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                fields=("niche", "phrase"), name="unique_phrase"
            ),
        ),
    ]
