# coding: utf-8

"""
    external/v1/auth_service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    NOTE
    ----
    standard swagger-codegen-cli for this python client has been modified
    by custom templates. The purpose of these templates is to include
    typing information in the API and Model code. Please refer to the
    main grid repository for more info
"""

import pprint
import re  # noqa: F401

from typing import TYPE_CHECKING

import six

if TYPE_CHECKING:
    from datetime import datetime
    from lightning_sdk.lightning_cloud.openapi.models import *

class V1ValidateDataConnectionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aws': 'V1AwsDataConnection',
        'efs': 'V1EfsDataConnection',
        'gcp': 'V1GcpDataConnection'
    }

    attribute_map = {
        'aws': 'aws',
        'efs': 'efs',
        'gcp': 'gcp'
    }

    def __init__(self, aws: 'V1AwsDataConnection' =None, efs: 'V1EfsDataConnection' =None, gcp: 'V1GcpDataConnection' =None):  # noqa: E501
        """V1ValidateDataConnectionResponse - a model defined in Swagger"""  # noqa: E501
        self._aws = None
        self._efs = None
        self._gcp = None
        self.discriminator = None
        if aws is not None:
            self.aws = aws
        if efs is not None:
            self.efs = efs
        if gcp is not None:
            self.gcp = gcp

    @property
    def aws(self) -> 'V1AwsDataConnection':
        """Gets the aws of this V1ValidateDataConnectionResponse.  # noqa: E501


        :return: The aws of this V1ValidateDataConnectionResponse.  # noqa: E501
        :rtype: V1AwsDataConnection
        """
        return self._aws

    @aws.setter
    def aws(self, aws: 'V1AwsDataConnection'):
        """Sets the aws of this V1ValidateDataConnectionResponse.


        :param aws: The aws of this V1ValidateDataConnectionResponse.  # noqa: E501
        :type: V1AwsDataConnection
        """

        self._aws = aws

    @property
    def efs(self) -> 'V1EfsDataConnection':
        """Gets the efs of this V1ValidateDataConnectionResponse.  # noqa: E501


        :return: The efs of this V1ValidateDataConnectionResponse.  # noqa: E501
        :rtype: V1EfsDataConnection
        """
        return self._efs

    @efs.setter
    def efs(self, efs: 'V1EfsDataConnection'):
        """Sets the efs of this V1ValidateDataConnectionResponse.


        :param efs: The efs of this V1ValidateDataConnectionResponse.  # noqa: E501
        :type: V1EfsDataConnection
        """

        self._efs = efs

    @property
    def gcp(self) -> 'V1GcpDataConnection':
        """Gets the gcp of this V1ValidateDataConnectionResponse.  # noqa: E501


        :return: The gcp of this V1ValidateDataConnectionResponse.  # noqa: E501
        :rtype: V1GcpDataConnection
        """
        return self._gcp

    @gcp.setter
    def gcp(self, gcp: 'V1GcpDataConnection'):
        """Sets the gcp of this V1ValidateDataConnectionResponse.


        :param gcp: The gcp of this V1ValidateDataConnectionResponse.  # noqa: E501
        :type: V1GcpDataConnection
        """

        self._gcp = gcp

    def to_dict(self) -> dict:
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1ValidateDataConnectionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self) -> str:
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self) -> str:
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other: 'V1ValidateDataConnectionResponse') -> bool:
        """Returns true if both objects are equal"""
        if not isinstance(other, V1ValidateDataConnectionResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other: 'V1ValidateDataConnectionResponse') -> bool:
        """Returns true if both objects are not equal"""
        return not self == other
