# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/common_msgs/sensor_msgs/radarpointcloud.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_modules.modules.common_msgs.basic_msgs import header_pb2 as modules_dot_common__msgs_dot_basic__msgs_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5modules/common_msgs/sensor_msgs/radarpointcloud.proto\x12\x0e\x61pollo.drivers\x1a+modules/common_msgs/basic_msgs/header.proto\"f\n\x0fRadarPointXYZVR\x12\x0e\n\x01x\x18\x01 \x01(\x02:\x03nan\x12\x0e\n\x01y\x18\x02 \x01(\x02:\x03nan\x12\x0e\n\x01z\x18\x03 \x01(\x02:\x03nan\x12\x13\n\x08velocity\x18\x04 \x01(\x02:\x01\x30\x12\x0e\n\x03rcs\x18\x05 \x01(\x02:\x01\x30\"\xc5\x01\n\x0fRadarPointCloud\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.apollo.common.Header\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x10\n\x08is_dense\x18\x03 \x01(\x08\x12.\n\x05point\x18\x04 \x03(\x0b\x32\x1f.apollo.drivers.RadarPointXYZVR\x12\x18\n\x10measurement_time\x18\x05 \x01(\x01\x12\r\n\x05width\x18\x06 \x01(\r\x12\x0e\n\x06height\x18\x07 \x01(\r')



_RADARPOINTXYZVR = DESCRIPTOR.message_types_by_name['RadarPointXYZVR']
_RADARPOINTCLOUD = DESCRIPTOR.message_types_by_name['RadarPointCloud']
RadarPointXYZVR = _reflection.GeneratedProtocolMessageType('RadarPointXYZVR', (_message.Message,), {
  'DESCRIPTOR' : _RADARPOINTXYZVR,
  '__module__' : 'modules.common_msgs.sensor_msgs.radarpointcloud_pb2'
  # @@protoc_insertion_point(class_scope:apollo.drivers.RadarPointXYZVR)
  })
_sym_db.RegisterMessage(RadarPointXYZVR)

RadarPointCloud = _reflection.GeneratedProtocolMessageType('RadarPointCloud', (_message.Message,), {
  'DESCRIPTOR' : _RADARPOINTCLOUD,
  '__module__' : 'modules.common_msgs.sensor_msgs.radarpointcloud_pb2'
  # @@protoc_insertion_point(class_scope:apollo.drivers.RadarPointCloud)
  })
_sym_db.RegisterMessage(RadarPointCloud)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RADARPOINTXYZVR._serialized_start=118
  _RADARPOINTXYZVR._serialized_end=220
  _RADARPOINTCLOUD._serialized_start=223
  _RADARPOINTCLOUD._serialized_end=420
# @@protoc_insertion_point(module_scope)
