"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from foxtail_trainer_client.api_client import ApiClient, Endpoint as _Endpoint
from foxtail_trainer_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from foxtail_trainer_client.model.job_metric_report_dto import JobMetricReportDto
from foxtail_trainer_client.model.ml_models_metric_list_report_dto import MLModelsMetricListReportDto
from foxtail_trainer_client.model.ml_models_status_counts_list_report_dto import MLModelsStatusCountsListReportDto
from foxtail_trainer_client.model.ml_models_status_list_report_dto import MLModelsStatusListReportDto
from foxtail_trainer_client.model.ml_models_url_list_report_dto import MLModelsUrlListReportDto
from foxtail_trainer_client.model.model_status import ModelStatus
from foxtail_trainer_client.model.training_time_report_dto import TrainingTimeReportDto


class ReportApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.api_job_job_id_report_get_job_metric_get_endpoint = _Endpoint(
            settings={
                'response_type': (JobMetricReportDto,),
                'auth': [],
                'endpoint_path': '/api/Job/{jobId}/Report/GetJobMetric',
                'operation_id': 'api_job_job_id_report_get_job_metric_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'job_id',
                    'filter_ml_models_by_guids',
                ],
                'required': [
                    'job_id',
                ],
                'nullable': [
                    'filter_ml_models_by_guids',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'job_id':
                        (str,),
                    'filter_ml_models_by_guids':
                        ([str], none_type,),
                },
                'attribute_map': {
                    'job_id': 'jobId',
                    'filter_ml_models_by_guids': 'filterMLModelsByGuids',
                },
                'location_map': {
                    'job_id': 'path',
                    'filter_ml_models_by_guids': 'query',
                },
                'collection_format_map': {
                    'filter_ml_models_by_guids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'text/plain',
                    'application/json',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.api_job_job_id_report_get_ml_models_metric_get_endpoint = _Endpoint(
            settings={
                'response_type': (MLModelsMetricListReportDto,),
                'auth': [],
                'endpoint_path': '/api/Job/{jobId}/Report/GetMLModelsMetric',
                'operation_id': 'api_job_job_id_report_get_ml_models_metric_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'job_id',
                    'filter_ml_models_by_guids',
                ],
                'required': [
                    'job_id',
                ],
                'nullable': [
                    'filter_ml_models_by_guids',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'job_id':
                        (str,),
                    'filter_ml_models_by_guids':
                        ([str], none_type,),
                },
                'attribute_map': {
                    'job_id': 'jobId',
                    'filter_ml_models_by_guids': 'filterMLModelsByGuids',
                },
                'location_map': {
                    'job_id': 'path',
                    'filter_ml_models_by_guids': 'query',
                },
                'collection_format_map': {
                    'filter_ml_models_by_guids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'text/plain',
                    'application/json',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.api_job_job_id_report_get_ml_models_status_counts_get_endpoint = _Endpoint(
            settings={
                'response_type': (MLModelsStatusCountsListReportDto,),
                'auth': [],
                'endpoint_path': '/api/Job/{jobId}/Report/GetMLModelsStatusCounts',
                'operation_id': 'api_job_job_id_report_get_ml_models_status_counts_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'job_id',
                    'model_status',
                    'filter_ml_models_by_guids',
                ],
                'required': [
                    'job_id',
                ],
                'nullable': [
                    'filter_ml_models_by_guids',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'job_id':
                        (str,),
                    'model_status':
                        (ModelStatus,),
                    'filter_ml_models_by_guids':
                        ([str], none_type,),
                },
                'attribute_map': {
                    'job_id': 'jobId',
                    'model_status': 'modelStatus',
                    'filter_ml_models_by_guids': 'filterMLModelsByGuids',
                },
                'location_map': {
                    'job_id': 'path',
                    'model_status': 'query',
                    'filter_ml_models_by_guids': 'query',
                },
                'collection_format_map': {
                    'filter_ml_models_by_guids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'text/plain',
                    'application/json',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.api_job_job_id_report_get_ml_models_status_get_endpoint = _Endpoint(
            settings={
                'response_type': (MLModelsStatusListReportDto,),
                'auth': [],
                'endpoint_path': '/api/Job/{jobId}/Report/GetMLModelsStatus',
                'operation_id': 'api_job_job_id_report_get_ml_models_status_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'job_id',
                    'filter_ml_models_by_guids',
                ],
                'required': [
                    'job_id',
                ],
                'nullable': [
                    'filter_ml_models_by_guids',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'job_id':
                        (str,),
                    'filter_ml_models_by_guids':
                        ([str], none_type,),
                },
                'attribute_map': {
                    'job_id': 'jobId',
                    'filter_ml_models_by_guids': 'filterMLModelsByGuids',
                },
                'location_map': {
                    'job_id': 'path',
                    'filter_ml_models_by_guids': 'query',
                },
                'collection_format_map': {
                    'filter_ml_models_by_guids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'text/plain',
                    'application/json',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.api_job_job_id_report_get_ml_models_url_get_endpoint = _Endpoint(
            settings={
                'response_type': (MLModelsUrlListReportDto,),
                'auth': [],
                'endpoint_path': '/api/Job/{jobId}/Report/GetMLModelsUrl',
                'operation_id': 'api_job_job_id_report_get_ml_models_url_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'job_id',
                    'filter_ml_models_by_guids',
                ],
                'required': [
                    'job_id',
                ],
                'nullable': [
                    'filter_ml_models_by_guids',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'job_id':
                        (str,),
                    'filter_ml_models_by_guids':
                        ([str], none_type,),
                },
                'attribute_map': {
                    'job_id': 'jobId',
                    'filter_ml_models_by_guids': 'filterMLModelsByGuids',
                },
                'location_map': {
                    'job_id': 'path',
                    'filter_ml_models_by_guids': 'query',
                },
                'collection_format_map': {
                    'filter_ml_models_by_guids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'text/plain',
                    'application/json',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.api_job_job_id_report_get_training_time_get_endpoint = _Endpoint(
            settings={
                'response_type': (TrainingTimeReportDto,),
                'auth': [],
                'endpoint_path': '/api/Job/{jobId}/Report/GetTrainingTime',
                'operation_id': 'api_job_job_id_report_get_training_time_get',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'job_id',
                    'filter_ml_models_by_guids',
                ],
                'required': [
                    'job_id',
                ],
                'nullable': [
                    'filter_ml_models_by_guids',
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'job_id':
                        (str,),
                    'filter_ml_models_by_guids':
                        ([str], none_type,),
                },
                'attribute_map': {
                    'job_id': 'jobId',
                    'filter_ml_models_by_guids': 'filterMLModelsByGuids',
                },
                'location_map': {
                    'job_id': 'path',
                    'filter_ml_models_by_guids': 'query',
                },
                'collection_format_map': {
                    'filter_ml_models_by_guids': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'text/plain',
                    'application/json',
                    'text/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )

    def api_job_job_id_report_get_job_metric_get(
        self,
        job_id,
        **kwargs
    ):
        """api_job_job_id_report_get_job_metric_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_job_job_id_report_get_job_metric_get(job_id, async_req=True)
        >>> result = thread.get()

        Args:
            job_id (str):

        Keyword Args:
            filter_ml_models_by_guids ([str], none_type): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            JobMetricReportDto
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['job_id'] = \
            job_id
        return self.api_job_job_id_report_get_job_metric_get_endpoint.call_with_http_info(**kwargs)

    def api_job_job_id_report_get_ml_models_metric_get(
        self,
        job_id,
        **kwargs
    ):
        """api_job_job_id_report_get_ml_models_metric_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_job_job_id_report_get_ml_models_metric_get(job_id, async_req=True)
        >>> result = thread.get()

        Args:
            job_id (str):

        Keyword Args:
            filter_ml_models_by_guids ([str], none_type): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            MLModelsMetricListReportDto
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['job_id'] = \
            job_id
        return self.api_job_job_id_report_get_ml_models_metric_get_endpoint.call_with_http_info(**kwargs)

    def api_job_job_id_report_get_ml_models_status_counts_get(
        self,
        job_id,
        **kwargs
    ):
        """api_job_job_id_report_get_ml_models_status_counts_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_job_job_id_report_get_ml_models_status_counts_get(job_id, async_req=True)
        >>> result = thread.get()

        Args:
            job_id (str):

        Keyword Args:
            model_status (ModelStatus): [optional]
            filter_ml_models_by_guids ([str], none_type): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            MLModelsStatusCountsListReportDto
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['job_id'] = \
            job_id
        return self.api_job_job_id_report_get_ml_models_status_counts_get_endpoint.call_with_http_info(**kwargs)

    def api_job_job_id_report_get_ml_models_status_get(
        self,
        job_id,
        **kwargs
    ):
        """Get status for every model. Report contains model id and current status.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_job_job_id_report_get_ml_models_status_get(job_id, async_req=True)
        >>> result = thread.get()

        Args:
            job_id (str): 

        Keyword Args:
            filter_ml_models_by_guids ([str], none_type): . [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            MLModelsStatusListReportDto
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['job_id'] = \
            job_id
        return self.api_job_job_id_report_get_ml_models_status_get_endpoint.call_with_http_info(**kwargs)

    def api_job_job_id_report_get_ml_models_url_get(
        self,
        job_id,
        **kwargs
    ):
        """  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_job_job_id_report_get_ml_models_url_get(job_id, async_req=True)
        >>> result = thread.get()

        Args:
            job_id (str): 

        Keyword Args:
            filter_ml_models_by_guids ([str], none_type): . [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            MLModelsUrlListReportDto
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['job_id'] = \
            job_id
        return self.api_job_job_id_report_get_ml_models_url_get_endpoint.call_with_http_info(**kwargs)

    def api_job_job_id_report_get_training_time_get(
        self,
        job_id,
        **kwargs
    ):
        """api_job_job_id_report_get_training_time_get  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_job_job_id_report_get_training_time_get(job_id, async_req=True)
        >>> result = thread.get()

        Args:
            job_id (str):

        Keyword Args:
            filter_ml_models_by_guids ([str], none_type): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            _request_auths (list): set to override the auth_settings for an a single
                request; this effectively ignores the authentication
                in the spec for a single request.
                Default is None
            async_req (bool): execute request asynchronously

        Returns:
            TrainingTimeReportDto
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['_request_auths'] = kwargs.get('_request_auths', None)
        kwargs['job_id'] = \
            job_id
        return self.api_job_job_id_report_get_training_time_get_endpoint.call_with_http_info(**kwargs)

