from typing import overload
import ghidra.pty
import java.lang
import java.util.concurrent


class SshPtySession(object, ghidra.pty.PtySession):




    def __init__(self, channel: com.jcraft.jsch.Channel): ...



    def description(self) -> unicode: ...

    def destroyForcibly(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @overload
    def waitExited(self) -> int: ...

    @overload
    def waitExited(self, timeout: long, unit: java.util.concurrent.TimeUnit) -> int: ...

