
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-23T14:29:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "df4bb7aa3bb0c6215ac8791b03543462a9c9d031",
 "version": "3.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
