# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/traffic_light_recognition/proto/traffic_light_recognition_component.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from apollo_modules.modules.perception.common.proto import plugin_param_pb2 as modules_dot_perception_dot_common_dot_proto_dot_plugin__param__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\\modules/perception/traffic_light_recognition/proto/traffic_light_recognition_component.proto\x12\x1e\x61pollo.perception.trafficlight\x1a\x32modules/perception/common/proto/plugin_param.proto\"\x81\x01\n\x10RecognitionParam\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\x12\x34\n\x0cplugin_param\x18\x02 \x01(\x0b\x32\x1e.apollo.perception.PluginParam\x12\'\n\x1frecognition_output_channel_name\x18\x03 \x01(\t')



_RECOGNITIONPARAM = DESCRIPTOR.message_types_by_name['RecognitionParam']
RecognitionParam = _reflection.GeneratedProtocolMessageType('RecognitionParam', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNITIONPARAM,
  '__module__' : 'modules.perception.traffic_light_recognition.proto.traffic_light_recognition_component_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.trafficlight.RecognitionParam)
  })
_sym_db.RegisterMessage(RecognitionParam)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RECOGNITIONPARAM._serialized_start=181
  _RECOGNITIONPARAM._serialized_end=310
# @@protoc_insertion_point(module_scope)
