# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/planning/planning_interface_base/scenario_base/proto/creep_stage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNmodules/planning/planning_interface_base/scenario_base/proto/creep_stage.proto\x12\x0f\x61pollo.planning\"p\n\x10\x43reepStageConfig\x12\x19\n\x0emin_boundary_t\x18\x01 \x01(\x01:\x01\x36\x12 \n\x13ignore_max_st_min_t\x18\x02 \x01(\x01:\x03\x30.1\x12\x1f\n\x13ignore_min_st_min_s\x18\x03 \x01(\x01:\x02\x31\x35')



_CREEPSTAGECONFIG = DESCRIPTOR.message_types_by_name['CreepStageConfig']
CreepStageConfig = _reflection.GeneratedProtocolMessageType('CreepStageConfig', (_message.Message,), {
  'DESCRIPTOR' : _CREEPSTAGECONFIG,
  '__module__' : 'modules.planning.planning_interface_base.scenario_base.proto.creep_stage_pb2'
  # @@protoc_insertion_point(class_scope:apollo.planning.CreepStageConfig)
  })
_sym_db.RegisterMessage(CreepStageConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREEPSTAGECONFIG._serialized_start=99
  _CREEPSTAGECONFIG._serialized_end=211
# @@protoc_insertion_point(module_scope)
