
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-04T05:26:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfa16a96fff542dfc3a73168b998bea1018b1d9c",
 "version": "1.30.0.post0.dev111"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
