from typing import overload
import ghidra.features.base.codecompare.panel
import ghidra.program.model.address
import ghidra.program.model.listing
import java.lang


class FunctionComparisonData(object, ghidra.features.base.codecompare.panel.ComparisonData):
    """
    ComparisonData for a function
    """

    EMPTY: ghidra.features.base.codecompare.panel.ComparisonData
    FG_COLOR_TITLE: java.awt.Color



    def __init__(self, function: ghidra.program.model.listing.Function): ...



    def equals(self, __a0: object) -> bool: ...

    def getAddressSet(self) -> ghidra.program.model.address.AddressSetView: ...

    def getClass(self) -> java.lang.Class: ...

    def getDescription(self) -> unicode: ...

    def getFunction(self) -> ghidra.program.model.listing.Function: ...

    def getProgram(self) -> ghidra.program.model.listing.Program: ...

    def getShortDescription(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isEmpty(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def addressSet(self) -> ghidra.program.model.address.AddressSetView: ...

    @property
    def description(self) -> unicode: ...

    @property
    def empty(self) -> bool: ...

    @property
    def function(self) -> ghidra.program.model.listing.Function: ...

    @property
    def program(self) -> ghidra.program.model.listing.Program: ...

    @property
    def shortDescription(self) -> unicode: ...