from typing import overload
import ghidra.pty.windows
import java.lang


class Pipe(object):








    def close(self) -> None: ...

    @staticmethod
    def createPipe() -> ghidra.pty.windows.Pipe: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getReadHandle(self) -> ghidra.pty.windows.Handle: ...

    def getWriteHandle(self) -> ghidra.pty.windows.Handle: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def readHandle(self) -> ghidra.pty.windows.Handle: ...

    @property
    def writeHandle(self) -> ghidra.pty.windows.Handle: ...