from typing import overload
import com.sun.jna.platform.win32.WinNT
import ghidra.pty.windows
import java.lang


class PseudoConsoleHandle(ghidra.pty.windows.Handle):




    def __init__(self, handle: com.sun.jna.platform.win32.WinNT.HANDLE): ...



    def close(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getNative(self) -> com.sun.jna.platform.win32.WinNT.HANDLE: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def resize(self, rows: int, cols: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

