from typing import overload
import java.lang
import java.util


class DBStringMapAdapter(object):
    """
    DBStringMapAdapter provides a simple string-to-string map backed by a named database table.
     This adapter's schema must never change.
    """





    def __init__(self, dbHandle: db.DBHandle, tableName: unicode, create: bool): ...



    def delete(self, key: unicode) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def get(self, key: unicode) -> unicode: ...

    def getBoolean(self, key: unicode, defaultValue: bool) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getInt(self, key: unicode, defaultValue: int) -> int: ...

    def hashCode(self) -> int: ...

    def keySet(self) -> java.util.Set: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def put(self, key: unicode, value: unicode) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

