# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/foodplate',
                'doc_host': 'https://aiforhealth-xyz.github.io',
                'git_url': 'https://github.com/aiforhealth-xyz/foodplate',
                'lib_path': 'foodplate'},
  'syms': {'foodplate.core': {'foodplate.core.foo': ('core.html#foo', 'foodplate/core.py')}}}