
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-03T02:29:11+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c70fbd8ff919cabaacfabcbdbf28aa435ae622f9",
 "version": "1.5.dev2444"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
