class String:
    def __init__(self, initial: str): ...
    def __str__(self) -> str: ...
    def __len__(self) -> int: ...
    def __add__(self, other: 'String') -> 'String': ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, key: int) -> str: ...
    def __iter__(self) -> str: ...
    def __repr__(self) -> str: ...

    def to_upper(self) -> 'String': ...
    def to_lower(self) -> 'String': ...
    def capitalize(self) -> 'String': ...
    def reverse(self) -> 'String': ...
    def contains(self, substring: str) -> bool: ...
    def split(self, delimiter: str = " ") -> list['String']: ...
    def join(self, iterable: list['String']) -> 'String': ...
    def format(self, *args: any, **kwargs: any) -> 'String': ...
    def replace(self, old: str, new: str, count: int = -1) -> 'String': ...
    def strip(self) -> 'String': ...
    def starts_with(self, prefix: str) -> bool: ...
    def ends_with(self, suffix: str) -> bool: ...
