# coding: utf-8

"""
    Secore API

    API for the Seres core platform

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seres_client.api.flight_plan_waypoints_api import FlightPlanWaypointsApi


class TestFlightPlanWaypointsApi(unittest.TestCase):
    """FlightPlanWaypointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlightPlanWaypointsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_flight_plan_waypoint(self) -> None:
        """Test case for cancel_flight_plan_waypoint

        Cancel Flight Plan Waypoint
        """
        pass

    def test_create_flight_plan_waypoint(self) -> None:
        """Test case for create_flight_plan_waypoint

        Create Flight Plan Waypoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
