"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import foxtail_trainer_client
from foxtail_trainer_client.model.job_training_config_dto import JobTrainingConfigDto
globals()['JobTrainingConfigDto'] = JobTrainingConfigDto
from foxtail_trainer_client.model.update_job_training_config_command import UpdateJobTrainingConfigCommand


class TestUpdateJobTrainingConfigCommand(unittest.TestCase):
    """UpdateJobTrainingConfigCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateJobTrainingConfigCommand(self):
        """Test UpdateJobTrainingConfigCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UpdateJobTrainingConfigCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
