"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import foxtail_trainer_client
from foxtail_trainer_client.model.prediction_status import PredictionStatus
globals()['PredictionStatus'] = PredictionStatus
from foxtail_trainer_client.model.data_set_chunk_basic_dto import DataSetChunkBasicDto


class TestDataSetChunkBasicDto(unittest.TestCase):
    """DataSetChunkBasicDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataSetChunkBasicDto(self):
        """Test DataSetChunkBasicDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DataSetChunkBasicDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
