"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import foxtail_trainer_client
from foxtail_trainer_client.model.model_status import ModelStatus
globals()['ModelStatus'] = ModelStatus
from foxtail_trainer_client.model.ml_models_status_report_dto import MLModelsStatusReportDto


class TestMLModelsStatusReportDto(unittest.TestCase):
    """MLModelsStatusReportDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMLModelsStatusReportDto(self):
        """Test MLModelsStatusReportDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MLModelsStatusReportDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
