"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import foxtail_trainer_client
from foxtail_trainer_client.model.training_history_dto import TrainingHistoryDto


class TestTrainingHistoryDto(unittest.TestCase):
    """TrainingHistoryDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrainingHistoryDto(self):
        """Test TrainingHistoryDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrainingHistoryDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
