"""
    Foxtail Trainer

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import unittest

import foxtail_trainer_client
from foxtail_trainer_client.api.worker_api import WorkerApi  # noqa: E501


class TestWorkerApi(unittest.TestCase):
    """WorkerApi unit test stubs"""

    def setUp(self):
        self.api = WorkerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_job_job_id_worker_get(self):
        """Test case for api_job_job_id_worker_get

        """
        pass

    def test_api_job_job_id_worker_worker_id_get(self):
        """Test case for api_job_job_id_worker_worker_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
