# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/external_command/external_command_demo/proto/sweeper_custom_command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nQmodules/external_command/external_command_demo/proto/sweeper_custom_command.proto\x12\x17\x61pollo.external_command\"O\n\x14SweeperCustomCommand\x12\x1f\n\x10is_turn_on_brush\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x16\n\x0esweeping_speed\x18\x02 \x01(\x01')



_SWEEPERCUSTOMCOMMAND = DESCRIPTOR.message_types_by_name['SweeperCustomCommand']
SweeperCustomCommand = _reflection.GeneratedProtocolMessageType('SweeperCustomCommand', (_message.Message,), {
  'DESCRIPTOR' : _SWEEPERCUSTOMCOMMAND,
  '__module__' : 'modules.external_command.external_command_demo.proto.sweeper_custom_command_pb2'
  # @@protoc_insertion_point(class_scope:apollo.external_command.SweeperCustomCommand)
  })
_sym_db.RegisterMessage(SweeperCustomCommand)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SWEEPERCUSTOMCOMMAND._serialized_start=110
  _SWEEPERCUSTOMCOMMAND._serialized_end=189
# @@protoc_insertion_point(module_scope)
